// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IdentityID represents a unique identifier for an identity in the network.
type IdentityID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityID) Reset() {
	*x = IdentityID{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityID) ProtoMessage() {}

func (x *IdentityID) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityID.ProtoReflect.Descriptor instead.
func (*IdentityID) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// IdentityMeta contains metadata associated with an identity.
type IdentityMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *IdentityID            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityMeta) Reset() {
	*x = IdentityMeta{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityMeta) ProtoMessage() {}

func (x *IdentityMeta) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityMeta.ProtoReflect.Descriptor instead.
func (*IdentityMeta) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityMeta) GetId() *IdentityID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IdentityMeta) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *IdentityMeta) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *IdentityMeta) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IdentityMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *IdentityMeta) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// Signature represents a cryptographic signature with metadata.
type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Signature) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *Signature) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Signature) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Credential represents a verifiable claim or capability.
type Credential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Issuer        *IdentityID            `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       *IdentityID            `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,4,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // optional
	Signature     *Signature             `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credential) Reset() {
	*x = Credential{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credential) ProtoMessage() {}

func (x *Credential) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credential.ProtoReflect.Descriptor instead.
func (*Credential) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *Credential) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Credential) GetIssuer() *IdentityID {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *Credential) GetSubject() *IdentityID {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Credential) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *Credential) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Credential) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Credential) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// IdentityCreateRequest represents a request to create a new identity.
type IdentityCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    map[string]string      `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityCreateRequest) Reset() {
	*x = IdentityCreateRequest{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityCreateRequest) ProtoMessage() {}

func (x *IdentityCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityCreateRequest.ProtoReflect.Descriptor instead.
func (*IdentityCreateRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *IdentityCreateRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// IdentityUpdateRequest represents a request to update identity metadata.
type IdentityUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *IdentityID            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityUpdateRequest) Reset() {
	*x = IdentityUpdateRequest{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityUpdateRequest) ProtoMessage() {}

func (x *IdentityUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityUpdateRequest.ProtoReflect.Descriptor instead.
func (*IdentityUpdateRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *IdentityUpdateRequest) GetId() *IdentityID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *IdentityUpdateRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// IdentityResolveRequest represents a request to resolve identity metadata.
type IdentityResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []*IdentityID          `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResolveRequest) Reset() {
	*x = IdentityResolveRequest{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResolveRequest) ProtoMessage() {}

func (x *IdentityResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResolveRequest.ProtoReflect.Descriptor instead.
func (*IdentityResolveRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *IdentityResolveRequest) GetIds() []*IdentityID {
	if x != nil {
		return x.Ids
	}
	return nil
}

// IdentityResolveResponse represents the response to identity resolution.
type IdentityResolveResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Identities    map[string]*IdentityMeta `protobuf:"bytes,1,rep,name=identities,proto3" json:"identities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key is IdentityID.value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResolveResponse) Reset() {
	*x = IdentityResolveResponse{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResolveResponse) ProtoMessage() {}

func (x *IdentityResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResolveResponse.ProtoReflect.Descriptor instead.
func (*IdentityResolveResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *IdentityResolveResponse) GetIdentities() map[string]*IdentityMeta {
	if x != nil {
		return x.Identities
	}
	return nil
}

// SignRequest represents a request to sign data.
type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *SignRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SignResponse represents the response to a sign request.
type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     *Signature             `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{9}
}

func (x *SignResponse) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// VerifyRequest represents a request to verify a signature.
type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	IdentityId    *IdentityID            `protobuf:"bytes,3,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VerifyRequest) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VerifyRequest) GetIdentityId() *IdentityID {
	if x != nil {
		return x.IdentityId
	}
	return nil
}

// VerifyResponse represents the response to a verify request.
type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CredentialIssueRequest represents a request to issue a credential.
type CredentialIssueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *IdentityID            `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Claims        map[string]string      `protobuf:"bytes,2,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // Time to live in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialIssueRequest) Reset() {
	*x = CredentialIssueRequest{}
	mi := &file_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialIssueRequest) ProtoMessage() {}

func (x *CredentialIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialIssueRequest.ProtoReflect.Descriptor instead.
func (*CredentialIssueRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{12}
}

func (x *CredentialIssueRequest) GetSubject() *IdentityID {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CredentialIssueRequest) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *CredentialIssueRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

// CredentialVerifyRequest represents a request to verify a credential.
type CredentialVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *Credential            `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialVerifyRequest) Reset() {
	*x = CredentialVerifyRequest{}
	mi := &file_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialVerifyRequest) ProtoMessage() {}

func (x *CredentialVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialVerifyRequest.ProtoReflect.Descriptor instead.
func (*CredentialVerifyRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{13}
}

func (x *CredentialVerifyRequest) GetCredential() *Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

// CredentialVerifyResponse represents the response to credential verification.
type CredentialVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialVerifyResponse) Reset() {
	*x = CredentialVerifyResponse{}
	mi := &file_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialVerifyResponse) ProtoMessage() {}

func (x *CredentialVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialVerifyResponse.ProtoReflect.Descriptor instead.
func (*CredentialVerifyResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{14}
}

func (x *CredentialVerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *CredentialVerifyResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// CredentialListRequest represents a request to list credentials.
type CredentialListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       *IdentityID            `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialListRequest) Reset() {
	*x = CredentialListRequest{}
	mi := &file_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialListRequest) ProtoMessage() {}

func (x *CredentialListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialListRequest.ProtoReflect.Descriptor instead.
func (*CredentialListRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{15}
}

func (x *CredentialListRequest) GetSubject() *IdentityID {
	if x != nil {
		return x.Subject
	}
	return nil
}

// CredentialListResponse represents the response to credential listing.
type CredentialListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   []*Credential          `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialListResponse) Reset() {
	*x = CredentialListResponse{}
	mi := &file_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialListResponse) ProtoMessage() {}

func (x *CredentialListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialListResponse.ProtoReflect.Descriptor instead.
func (*CredentialListResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{16}
}

func (x *CredentialListResponse) GetCredentials() []*Credential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\x0epeers_touch.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n" +
	"\n" +
	"IdentityID\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x97\x03\n" +
	"\fIdentityMeta\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12L\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2,.peers_touch.v2.IdentityMeta.AttributesEntryR\n" +
	"attributes\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x01\n" +
	"\tSignature\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xae\x03\n" +
	"\n" +
	"Credential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x06issuer\x18\x02 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\x06issuer\x124\n" +
	"\asubject\x18\x03 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\asubject\x12>\n" +
	"\x06claims\x18\x04 \x03(\v2&.peers_touch.v2.Credential.ClaimsEntryR\x06claims\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\tsignature\x18\a \x01(\v2\x19.peers_touch.v2.SignatureR\tsignature\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xad\x01\n" +
	"\x15IdentityCreateRequest\x12U\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v25.peers_touch.v2.IdentityCreateRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd9\x01\n" +
	"\x15IdentityUpdateRequest\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\x02id\x12U\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v25.peers_touch.v2.IdentityUpdateRequest.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x16IdentityResolveRequest\x12,\n" +
	"\x03ids\x18\x01 \x03(\v2\x1a.peers_touch.v2.IdentityIDR\x03ids\"\xcf\x01\n" +
	"\x17IdentityResolveResponse\x12W\n" +
	"\n" +
	"identities\x18\x01 \x03(\v27.peers_touch.v2.IdentityResolveResponse.IdentitiesEntryR\n" +
	"identities\x1a[\n" +
	"\x0fIdentitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.peers_touch.v2.IdentityMetaR\x05value:\x028\x01\"'\n" +
	"\vSignRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"G\n" +
	"\fSignResponse\x127\n" +
	"\tsignature\x18\x01 \x01(\v2\x19.peers_touch.v2.SignatureR\tsignature\"\x9f\x01\n" +
	"\rVerifyRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x127\n" +
	"\tsignature\x18\x02 \x01(\v2\x19.peers_touch.v2.SignatureR\tsignature\x12;\n" +
	"\videntity_id\x18\x03 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\n" +
	"identityId\"K\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xf6\x01\n" +
	"\x16CredentialIssueRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\asubject\x12J\n" +
	"\x06claims\x18\x02 \x03(\v22.peers_touch.v2.CredentialIssueRequest.ClaimsEntryR\x06claims\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x17CredentialVerifyRequest\x12:\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1a.peers_touch.v2.CredentialR\n" +
	"credential\"U\n" +
	"\x18CredentialVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"M\n" +
	"\x15CredentialListRequest\x124\n" +
	"\asubject\x18\x01 \x01(\v2\x1a.peers_touch.v2.IdentityIDR\asubject\"V\n" +
	"\x16CredentialListResponse\x12<\n" +
	"\vcredentials\x18\x01 \x03(\v2\x1a.peers_touch.v2.CredentialR\vcredentialsB6Z4github.com/peers-touch/peers-touch-proto/v2/identityb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_identity_proto_goTypes = []any{
	(*IdentityID)(nil),               // 0: peers_touch.v2.IdentityID
	(*IdentityMeta)(nil),             // 1: peers_touch.v2.IdentityMeta
	(*Signature)(nil),                // 2: peers_touch.v2.Signature
	(*Credential)(nil),               // 3: peers_touch.v2.Credential
	(*IdentityCreateRequest)(nil),    // 4: peers_touch.v2.IdentityCreateRequest
	(*IdentityUpdateRequest)(nil),    // 5: peers_touch.v2.IdentityUpdateRequest
	(*IdentityResolveRequest)(nil),   // 6: peers_touch.v2.IdentityResolveRequest
	(*IdentityResolveResponse)(nil),  // 7: peers_touch.v2.IdentityResolveResponse
	(*SignRequest)(nil),              // 8: peers_touch.v2.SignRequest
	(*SignResponse)(nil),             // 9: peers_touch.v2.SignResponse
	(*VerifyRequest)(nil),            // 10: peers_touch.v2.VerifyRequest
	(*VerifyResponse)(nil),           // 11: peers_touch.v2.VerifyResponse
	(*CredentialIssueRequest)(nil),   // 12: peers_touch.v2.CredentialIssueRequest
	(*CredentialVerifyRequest)(nil),  // 13: peers_touch.v2.CredentialVerifyRequest
	(*CredentialVerifyResponse)(nil), // 14: peers_touch.v2.CredentialVerifyResponse
	(*CredentialListRequest)(nil),    // 15: peers_touch.v2.CredentialListRequest
	(*CredentialListResponse)(nil),   // 16: peers_touch.v2.CredentialListResponse
	nil,                              // 17: peers_touch.v2.IdentityMeta.AttributesEntry
	nil,                              // 18: peers_touch.v2.Credential.ClaimsEntry
	nil,                              // 19: peers_touch.v2.IdentityCreateRequest.AttributesEntry
	nil,                              // 20: peers_touch.v2.IdentityUpdateRequest.AttributesEntry
	nil,                              // 21: peers_touch.v2.IdentityResolveResponse.IdentitiesEntry
	nil,                              // 22: peers_touch.v2.CredentialIssueRequest.ClaimsEntry
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
}
var file_identity_proto_depIdxs = []int32{
	0,  // 0: peers_touch.v2.IdentityMeta.id:type_name -> peers_touch.v2.IdentityID
	17, // 1: peers_touch.v2.IdentityMeta.attributes:type_name -> peers_touch.v2.IdentityMeta.AttributesEntry
	23, // 2: peers_touch.v2.IdentityMeta.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: peers_touch.v2.IdentityMeta.updated_at:type_name -> google.protobuf.Timestamp
	23, // 4: peers_touch.v2.IdentityMeta.expires_at:type_name -> google.protobuf.Timestamp
	23, // 5: peers_touch.v2.Signature.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: peers_touch.v2.Credential.issuer:type_name -> peers_touch.v2.IdentityID
	0,  // 7: peers_touch.v2.Credential.subject:type_name -> peers_touch.v2.IdentityID
	18, // 8: peers_touch.v2.Credential.claims:type_name -> peers_touch.v2.Credential.ClaimsEntry
	23, // 9: peers_touch.v2.Credential.issued_at:type_name -> google.protobuf.Timestamp
	23, // 10: peers_touch.v2.Credential.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 11: peers_touch.v2.Credential.signature:type_name -> peers_touch.v2.Signature
	19, // 12: peers_touch.v2.IdentityCreateRequest.attributes:type_name -> peers_touch.v2.IdentityCreateRequest.AttributesEntry
	0,  // 13: peers_touch.v2.IdentityUpdateRequest.id:type_name -> peers_touch.v2.IdentityID
	20, // 14: peers_touch.v2.IdentityUpdateRequest.attributes:type_name -> peers_touch.v2.IdentityUpdateRequest.AttributesEntry
	0,  // 15: peers_touch.v2.IdentityResolveRequest.ids:type_name -> peers_touch.v2.IdentityID
	21, // 16: peers_touch.v2.IdentityResolveResponse.identities:type_name -> peers_touch.v2.IdentityResolveResponse.IdentitiesEntry
	2,  // 17: peers_touch.v2.SignResponse.signature:type_name -> peers_touch.v2.Signature
	2,  // 18: peers_touch.v2.VerifyRequest.signature:type_name -> peers_touch.v2.Signature
	0,  // 19: peers_touch.v2.VerifyRequest.identity_id:type_name -> peers_touch.v2.IdentityID
	0,  // 20: peers_touch.v2.CredentialIssueRequest.subject:type_name -> peers_touch.v2.IdentityID
	22, // 21: peers_touch.v2.CredentialIssueRequest.claims:type_name -> peers_touch.v2.CredentialIssueRequest.ClaimsEntry
	3,  // 22: peers_touch.v2.CredentialVerifyRequest.credential:type_name -> peers_touch.v2.Credential
	0,  // 23: peers_touch.v2.CredentialListRequest.subject:type_name -> peers_touch.v2.IdentityID
	3,  // 24: peers_touch.v2.CredentialListResponse.credentials:type_name -> peers_touch.v2.Credential
	1,  // 25: peers_touch.v2.IdentityResolveResponse.IdentitiesEntry.value:type_name -> peers_touch.v2.IdentityMeta
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
