// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/actor/actor.proto

package actorv1

import (
	v1 "github.com/peers-touch/peers-touch/proto/gen/touch/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor basic information
type Actor struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                        // Unique identifier
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                    // Actor type (Person, Service, Group, etc.)
	PreferredUsername string                 `protobuf:"bytes,3,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"` // Actor's preferred username
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                    // Actor's display name
	Summary           string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`                                              // Brief description of the actor
	Icon              string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`                                                    // Actor's avatar/profile picture URL
	Image             string                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`                                                  // Actor's header/banner image URL
	Inbox             string                 `protobuf:"bytes,8,opt,name=inbox,proto3" json:"inbox,omitempty"`                                                  // Actor's inbox endpoint
	Outbox            string                 `protobuf:"bytes,9,opt,name=outbox,proto3" json:"outbox,omitempty"`                                                // Actor's outbox endpoint
	Followers         string                 `protobuf:"bytes,10,opt,name=followers,proto3" json:"followers,omitempty"`                                         // Actor's followers collection endpoint
	Following         string                 `protobuf:"bytes,11,opt,name=following,proto3" json:"following,omitempty"`                                         // Actor's following collection endpoint
	Liked             string                 `protobuf:"bytes,12,opt,name=liked,proto3" json:"liked,omitempty"`                                                 // Actor's liked collection endpoint
	PublicKey         string                 `protobuf:"bytes,13,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`                        // Public key for HTTP signatures
	CreatedAt         string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                        // Actor creation time
	UpdatedAt         string                 `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                        // Actor last update time
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_touch_v1_actor_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Actor) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *Actor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Actor) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Actor) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Actor) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Actor) GetInbox() string {
	if x != nil {
		return x.Inbox
	}
	return ""
}

func (x *Actor) GetOutbox() string {
	if x != nil {
		return x.Outbox
	}
	return ""
}

func (x *Actor) GetFollowers() string {
	if x != nil {
		return x.Followers
	}
	return ""
}

func (x *Actor) GetFollowing() string {
	if x != nil {
		return x.Following
	}
	return ""
}

func (x *Actor) GetLiked() string {
	if x != nil {
		return x.Liked
	}
	return ""
}

func (x *Actor) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *Actor) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Actor) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Actor registration parameters
type ActorSignUpParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Actor name
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`       // Actor email
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // Actor password
	Passport      string                 `protobuf:"bytes,4,opt,name=passport,proto3" json:"passport,omitempty"` // Actor passport
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorSignUpParams) Reset() {
	*x = ActorSignUpParams{}
	mi := &file_touch_v1_actor_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorSignUpParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorSignUpParams) ProtoMessage() {}

func (x *ActorSignUpParams) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorSignUpParams.ProtoReflect.Descriptor instead.
func (*ActorSignUpParams) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ActorSignUpParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorSignUpParams) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActorSignUpParams) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ActorSignUpParams) GetPassport() string {
	if x != nil {
		return x.Passport
	}
	return ""
}

// Actor login parameters
type ActorLoginParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`       // Actor email
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Actor password
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorLoginParams) Reset() {
	*x = ActorLoginParams{}
	mi := &file_touch_v1_actor_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorLoginParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorLoginParams) ProtoMessage() {}

func (x *ActorLoginParams) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorLoginParams.ProtoReflect.Descriptor instead.
func (*ActorLoginParams) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_actor_proto_rawDescGZIP(), []int{2}
}

func (x *ActorLoginParams) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActorLoginParams) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Actor authentication response
type ActorAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *Actor                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`                          // Actor information
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                          // Authentication token
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Token expiration time
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorAuthResponse) Reset() {
	*x = ActorAuthResponse{}
	mi := &file_touch_v1_actor_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorAuthResponse) ProtoMessage() {}

func (x *ActorAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorAuthResponse.ProtoReflect.Descriptor instead.
func (*ActorAuthResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_actor_proto_rawDescGZIP(), []int{3}
}

func (x *ActorAuthResponse) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ActorAuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ActorAuthResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_touch_v1_actor_actor_proto protoreflect.FileDescriptor

const file_touch_v1_actor_actor_proto_rawDesc = "" +
	"\n" +
	"\x1atouch/v1/actor/actor.proto\x12\x1apeers_touch.touch.v1.actor\x1a\x14touch/v1/types.proto\"\x8f\x03\n" +
	"\x05Actor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12-\n" +
	"\x12preferred_username\x18\x03 \x01(\tR\x11preferredUsername\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\x12\x14\n" +
	"\x05image\x18\a \x01(\tR\x05image\x12\x14\n" +
	"\x05inbox\x18\b \x01(\tR\x05inbox\x12\x16\n" +
	"\x06outbox\x18\t \x01(\tR\x06outbox\x12\x1c\n" +
	"\tfollowers\x18\n" +
	" \x01(\tR\tfollowers\x12\x1c\n" +
	"\tfollowing\x18\v \x01(\tR\tfollowing\x12\x14\n" +
	"\x05liked\x18\f \x01(\tR\x05liked\x12\x1d\n" +
	"\n" +
	"public_key\x18\r \x01(\tR\tpublicKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAt\"u\n" +
	"\x11ActorSignUpParams\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1a\n" +
	"\bpassport\x18\x04 \x01(\tR\bpassport\"D\n" +
	"\x10ActorLoginParams\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x81\x01\n" +
	"\x11ActorAuthResponse\x127\n" +
	"\x05actor\x18\x01 \x01(\v2!.peers_touch.touch.v1.actor.ActorR\x05actor\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt2\xaf\x02\n" +
	"\fActorService\x12f\n" +
	"\x06SignUp\x12-.peers_touch.touch.v1.actor.ActorSignUpParams\x1a-.peers_touch.touch.v1.actor.ActorAuthResponse\x12d\n" +
	"\x05Login\x12,.peers_touch.touch.v1.actor.ActorLoginParams\x1a-.peers_touch.touch.v1.actor.ActorAuthResponse\x12Q\n" +
	"\x0fGetCurrentActor\x12\x1b.peers_touch.touch.v1.Empty\x1a!.peers_touch.touch.v1.actor.ActorBEZCgithub.com/peers-touch/peers-touch/proto/gen/touch/v1/actor;actorv1b\x06proto3"

var (
	file_touch_v1_actor_actor_proto_rawDescOnce sync.Once
	file_touch_v1_actor_actor_proto_rawDescData []byte
)

func file_touch_v1_actor_actor_proto_rawDescGZIP() []byte {
	file_touch_v1_actor_actor_proto_rawDescOnce.Do(func() {
		file_touch_v1_actor_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_actor_actor_proto_rawDesc), len(file_touch_v1_actor_actor_proto_rawDesc)))
	})
	return file_touch_v1_actor_actor_proto_rawDescData
}

var file_touch_v1_actor_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_touch_v1_actor_actor_proto_goTypes = []any{
	(*Actor)(nil),             // 0: peers_touch.touch.v1.actor.Actor
	(*ActorSignUpParams)(nil), // 1: peers_touch.touch.v1.actor.ActorSignUpParams
	(*ActorLoginParams)(nil),  // 2: peers_touch.touch.v1.actor.ActorLoginParams
	(*ActorAuthResponse)(nil), // 3: peers_touch.touch.v1.actor.ActorAuthResponse
	(*v1.Empty)(nil),          // 4: peers_touch.touch.v1.Empty
}
var file_touch_v1_actor_actor_proto_depIdxs = []int32{
	0, // 0: peers_touch.touch.v1.actor.ActorAuthResponse.actor:type_name -> peers_touch.touch.v1.actor.Actor
	1, // 1: peers_touch.touch.v1.actor.ActorService.SignUp:input_type -> peers_touch.touch.v1.actor.ActorSignUpParams
	2, // 2: peers_touch.touch.v1.actor.ActorService.Login:input_type -> peers_touch.touch.v1.actor.ActorLoginParams
	4, // 3: peers_touch.touch.v1.actor.ActorService.GetCurrentActor:input_type -> peers_touch.touch.v1.Empty
	3, // 4: peers_touch.touch.v1.actor.ActorService.SignUp:output_type -> peers_touch.touch.v1.actor.ActorAuthResponse
	3, // 5: peers_touch.touch.v1.actor.ActorService.Login:output_type -> peers_touch.touch.v1.actor.ActorAuthResponse
	0, // 6: peers_touch.touch.v1.actor.ActorService.GetCurrentActor:output_type -> peers_touch.touch.v1.actor.Actor
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_touch_v1_actor_actor_proto_init() }
func file_touch_v1_actor_actor_proto_init() {
	if File_touch_v1_actor_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_actor_actor_proto_rawDesc), len(file_touch_v1_actor_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_v1_actor_actor_proto_goTypes,
		DependencyIndexes: file_touch_v1_actor_actor_proto_depIdxs,
		MessageInfos:      file_touch_v1_actor_actor_proto_msgTypes,
	}.Build()
	File_touch_v1_actor_actor_proto = out.File
	file_touch_v1_actor_actor_proto_goTypes = nil
	file_touch_v1_actor_actor_proto_depIdxs = nil
}
