// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: touch/v1/actor/facade.proto

package actorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FacadeService_CreateActor_FullMethodName     = "/peers_touch.touch.v1.actor.FacadeService/CreateActor"
	FacadeService_GetActor_FullMethodName        = "/peers_touch.touch.v1.actor.FacadeService/GetActor"
	FacadeService_UpdateActor_FullMethodName     = "/peers_touch.touch.v1.actor.FacadeService/UpdateActor"
	FacadeService_DeleteActor_FullMethodName     = "/peers_touch.touch.v1.actor.FacadeService/DeleteActor"
	FacadeService_Follow_FullMethodName          = "/peers_touch.touch.v1.actor.FacadeService/Follow"
	FacadeService_Unfollow_FullMethodName        = "/peers_touch.touch.v1.actor.FacadeService/Unfollow"
	FacadeService_CreateActivity_FullMethodName  = "/peers_touch.touch.v1.actor.FacadeService/CreateActivity"
	FacadeService_GetActivity_FullMethodName     = "/peers_touch.touch.v1.actor.FacadeService/GetActivity"
	FacadeService_DeleteActivity_FullMethodName  = "/peers_touch.touch.v1.actor.FacadeService/DeleteActivity"
	FacadeService_Like_FullMethodName            = "/peers_touch.touch.v1.actor.FacadeService/Like"
	FacadeService_Unlike_FullMethodName          = "/peers_touch.touch.v1.actor.FacadeService/Unlike"
	FacadeService_Announce_FullMethodName        = "/peers_touch.touch.v1.actor.FacadeService/Announce"
	FacadeService_GetInbox_FullMethodName        = "/peers_touch.touch.v1.actor.FacadeService/GetInbox"
	FacadeService_GetOutbox_FullMethodName       = "/peers_touch.touch.v1.actor.FacadeService/GetOutbox"
	FacadeService_GetFollowers_FullMethodName    = "/peers_touch.touch.v1.actor.FacadeService/GetFollowers"
	FacadeService_GetFollowing_FullMethodName    = "/peers_touch.touch.v1.actor.FacadeService/GetFollowing"
	FacadeService_GetLiked_FullMethodName        = "/peers_touch.touch.v1.actor.FacadeService/GetLiked"
	FacadeService_SendActivity_FullMethodName    = "/peers_touch.touch.v1.actor.FacadeService/SendActivity"
	FacadeService_ReceiveActivity_FullMethodName = "/peers_touch.touch.v1.actor.FacadeService/ReceiveActivity"
	FacadeService_ForwardActivity_FullMethodName = "/peers_touch.touch.v1.actor.FacadeService/ForwardActivity"
)

// FacadeServiceClient is the client API for FacadeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Facade service definition
type FacadeServiceClient interface {
	// Create actor
	CreateActor(ctx context.Context, in *CreateActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Get actor
	GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Update actor
	UpdateActor(ctx context.Context, in *UpdateActorRequest, opts ...grpc.CallOption) (*Actor, error)
	// Delete actor
	DeleteActor(ctx context.Context, in *DeleteActorRequest, opts ...grpc.CallOption) (*DeleteActorResponse, error)
	// Follow operations
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	// Unfollow operations
	Unfollow(ctx context.Context, in *UnfollowRequest, opts ...grpc.CallOption) (*UnfollowResponse, error)
	// Create activity
	CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*Activity, error)
	// Get activity
	GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*Activity, error)
	// Delete activity
	DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error)
	// Like operations
	Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	// Unlike operations
	Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*UnlikeResponse, error)
	// Announce operations
	Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error)
	// Get inbox
	GetInbox(ctx context.Context, in *GetInboxRequest, opts ...grpc.CallOption) (*ItemCollection, error)
	// Get outbox
	GetOutbox(ctx context.Context, in *GetOutboxRequest, opts ...grpc.CallOption) (*ItemCollection, error)
	// Get followers
	GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*ItemCollection, error)
	// Get following
	GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*ItemCollection, error)
	// Get liked
	GetLiked(ctx context.Context, in *GetLikedRequest, opts ...grpc.CallOption) (*ItemCollection, error)
	// Send activity
	SendActivity(ctx context.Context, in *SendActivityRequest, opts ...grpc.CallOption) (*SendActivityResponse, error)
	// Receive activity
	ReceiveActivity(ctx context.Context, in *ReceiveActivityRequest, opts ...grpc.CallOption) (*ReceiveActivityResponse, error)
	// Forward activity
	ForwardActivity(ctx context.Context, in *ForwardActivityRequest, opts ...grpc.CallOption) (*ForwardActivityResponse, error)
}

type facadeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFacadeServiceClient(cc grpc.ClientConnInterface) FacadeServiceClient {
	return &facadeServiceClient{cc}
}

func (c *facadeServiceClient) CreateActor(ctx context.Context, in *CreateActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, FacadeService_CreateActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetActor(ctx context.Context, in *GetActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, FacadeService_GetActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) UpdateActor(ctx context.Context, in *UpdateActorRequest, opts ...grpc.CallOption) (*Actor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Actor)
	err := c.cc.Invoke(ctx, FacadeService_UpdateActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) DeleteActor(ctx context.Context, in *DeleteActorRequest, opts ...grpc.CallOption) (*DeleteActorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActorResponse)
	err := c.cc.Invoke(ctx, FacadeService_DeleteActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, FacadeService_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) Unfollow(ctx context.Context, in *UnfollowRequest, opts ...grpc.CallOption) (*UnfollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowResponse)
	err := c.cc.Invoke(ctx, FacadeService_Unfollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) CreateActivity(ctx context.Context, in *CreateActivityRequest, opts ...grpc.CallOption) (*Activity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activity)
	err := c.cc.Invoke(ctx, FacadeService_CreateActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetActivity(ctx context.Context, in *GetActivityRequest, opts ...grpc.CallOption) (*Activity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activity)
	err := c.cc.Invoke(ctx, FacadeService_GetActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) DeleteActivity(ctx context.Context, in *DeleteActivityRequest, opts ...grpc.CallOption) (*DeleteActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActivityResponse)
	err := c.cc.Invoke(ctx, FacadeService_DeleteActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, FacadeService_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) Unlike(ctx context.Context, in *UnlikeRequest, opts ...grpc.CallOption) (*UnlikeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlikeResponse)
	err := c.cc.Invoke(ctx, FacadeService_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) Announce(ctx context.Context, in *AnnounceRequest, opts ...grpc.CallOption) (*AnnounceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceResponse)
	err := c.cc.Invoke(ctx, FacadeService_Announce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetInbox(ctx context.Context, in *GetInboxRequest, opts ...grpc.CallOption) (*ItemCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCollection)
	err := c.cc.Invoke(ctx, FacadeService_GetInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetOutbox(ctx context.Context, in *GetOutboxRequest, opts ...grpc.CallOption) (*ItemCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCollection)
	err := c.cc.Invoke(ctx, FacadeService_GetOutbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetFollowers(ctx context.Context, in *GetFollowersRequest, opts ...grpc.CallOption) (*ItemCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCollection)
	err := c.cc.Invoke(ctx, FacadeService_GetFollowers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetFollowing(ctx context.Context, in *GetFollowingRequest, opts ...grpc.CallOption) (*ItemCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCollection)
	err := c.cc.Invoke(ctx, FacadeService_GetFollowing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) GetLiked(ctx context.Context, in *GetLikedRequest, opts ...grpc.CallOption) (*ItemCollection, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ItemCollection)
	err := c.cc.Invoke(ctx, FacadeService_GetLiked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) SendActivity(ctx context.Context, in *SendActivityRequest, opts ...grpc.CallOption) (*SendActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendActivityResponse)
	err := c.cc.Invoke(ctx, FacadeService_SendActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) ReceiveActivity(ctx context.Context, in *ReceiveActivityRequest, opts ...grpc.CallOption) (*ReceiveActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveActivityResponse)
	err := c.cc.Invoke(ctx, FacadeService_ReceiveActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facadeServiceClient) ForwardActivity(ctx context.Context, in *ForwardActivityRequest, opts ...grpc.CallOption) (*ForwardActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardActivityResponse)
	err := c.cc.Invoke(ctx, FacadeService_ForwardActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacadeServiceServer is the server API for FacadeService service.
// All implementations must embed UnimplementedFacadeServiceServer
// for forward compatibility.
//
// Facade service definition
type FacadeServiceServer interface {
	// Create actor
	CreateActor(context.Context, *CreateActorRequest) (*Actor, error)
	// Get actor
	GetActor(context.Context, *GetActorRequest) (*Actor, error)
	// Update actor
	UpdateActor(context.Context, *UpdateActorRequest) (*Actor, error)
	// Delete actor
	DeleteActor(context.Context, *DeleteActorRequest) (*DeleteActorResponse, error)
	// Follow operations
	Follow(context.Context, *FollowRequest) (*FollowResponse, error)
	// Unfollow operations
	Unfollow(context.Context, *UnfollowRequest) (*UnfollowResponse, error)
	// Create activity
	CreateActivity(context.Context, *CreateActivityRequest) (*Activity, error)
	// Get activity
	GetActivity(context.Context, *GetActivityRequest) (*Activity, error)
	// Delete activity
	DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error)
	// Like operations
	Like(context.Context, *LikeRequest) (*LikeResponse, error)
	// Unlike operations
	Unlike(context.Context, *UnlikeRequest) (*UnlikeResponse, error)
	// Announce operations
	Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error)
	// Get inbox
	GetInbox(context.Context, *GetInboxRequest) (*ItemCollection, error)
	// Get outbox
	GetOutbox(context.Context, *GetOutboxRequest) (*ItemCollection, error)
	// Get followers
	GetFollowers(context.Context, *GetFollowersRequest) (*ItemCollection, error)
	// Get following
	GetFollowing(context.Context, *GetFollowingRequest) (*ItemCollection, error)
	// Get liked
	GetLiked(context.Context, *GetLikedRequest) (*ItemCollection, error)
	// Send activity
	SendActivity(context.Context, *SendActivityRequest) (*SendActivityResponse, error)
	// Receive activity
	ReceiveActivity(context.Context, *ReceiveActivityRequest) (*ReceiveActivityResponse, error)
	// Forward activity
	ForwardActivity(context.Context, *ForwardActivityRequest) (*ForwardActivityResponse, error)
	mustEmbedUnimplementedFacadeServiceServer()
}

// UnimplementedFacadeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFacadeServiceServer struct{}

func (UnimplementedFacadeServiceServer) CreateActor(context.Context, *CreateActorRequest) (*Actor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActor not implemented")
}
func (UnimplementedFacadeServiceServer) GetActor(context.Context, *GetActorRequest) (*Actor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActor not implemented")
}
func (UnimplementedFacadeServiceServer) UpdateActor(context.Context, *UpdateActorRequest) (*Actor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateActor not implemented")
}
func (UnimplementedFacadeServiceServer) DeleteActor(context.Context, *DeleteActorRequest) (*DeleteActorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActor not implemented")
}
func (UnimplementedFacadeServiceServer) Follow(context.Context, *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedFacadeServiceServer) Unfollow(context.Context, *UnfollowRequest) (*UnfollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unfollow not implemented")
}
func (UnimplementedFacadeServiceServer) CreateActivity(context.Context, *CreateActivityRequest) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateActivity not implemented")
}
func (UnimplementedFacadeServiceServer) GetActivity(context.Context, *GetActivityRequest) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActivity not implemented")
}
func (UnimplementedFacadeServiceServer) DeleteActivity(context.Context, *DeleteActivityRequest) (*DeleteActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteActivity not implemented")
}
func (UnimplementedFacadeServiceServer) Like(context.Context, *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedFacadeServiceServer) Unlike(context.Context, *UnlikeRequest) (*UnlikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedFacadeServiceServer) Announce(context.Context, *AnnounceRequest) (*AnnounceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Announce not implemented")
}
func (UnimplementedFacadeServiceServer) GetInbox(context.Context, *GetInboxRequest) (*ItemCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInbox not implemented")
}
func (UnimplementedFacadeServiceServer) GetOutbox(context.Context, *GetOutboxRequest) (*ItemCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutbox not implemented")
}
func (UnimplementedFacadeServiceServer) GetFollowers(context.Context, *GetFollowersRequest) (*ItemCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowers not implemented")
}
func (UnimplementedFacadeServiceServer) GetFollowing(context.Context, *GetFollowingRequest) (*ItemCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowing not implemented")
}
func (UnimplementedFacadeServiceServer) GetLiked(context.Context, *GetLikedRequest) (*ItemCollection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiked not implemented")
}
func (UnimplementedFacadeServiceServer) SendActivity(context.Context, *SendActivityRequest) (*SendActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendActivity not implemented")
}
func (UnimplementedFacadeServiceServer) ReceiveActivity(context.Context, *ReceiveActivityRequest) (*ReceiveActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveActivity not implemented")
}
func (UnimplementedFacadeServiceServer) ForwardActivity(context.Context, *ForwardActivityRequest) (*ForwardActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForwardActivity not implemented")
}
func (UnimplementedFacadeServiceServer) mustEmbedUnimplementedFacadeServiceServer() {}
func (UnimplementedFacadeServiceServer) testEmbeddedByValue()                       {}

// UnsafeFacadeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FacadeServiceServer will
// result in compilation errors.
type UnsafeFacadeServiceServer interface {
	mustEmbedUnimplementedFacadeServiceServer()
}

func RegisterFacadeServiceServer(s grpc.ServiceRegistrar, srv FacadeServiceServer) {
	// If the following call pancis, it indicates UnimplementedFacadeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FacadeService_ServiceDesc, srv)
}

func _FacadeService_CreateActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).CreateActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_CreateActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).CreateActor(ctx, req.(*CreateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetActor(ctx, req.(*GetActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_UpdateActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).UpdateActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_UpdateActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).UpdateActor(ctx, req.(*UpdateActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_DeleteActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).DeleteActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_DeleteActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).DeleteActor(ctx, req.(*DeleteActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_Unfollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).Unfollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_Unfollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).Unfollow(ctx, req.(*UnfollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_CreateActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).CreateActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_CreateActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).CreateActivity(ctx, req.(*CreateActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetActivity(ctx, req.(*GetActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_DeleteActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).DeleteActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_DeleteActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).DeleteActivity(ctx, req.(*DeleteActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).Like(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).Unlike(ctx, req.(*UnlikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_Announce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).Announce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_Announce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).Announce(ctx, req.(*AnnounceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetInbox(ctx, req.(*GetInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetOutbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOutboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetOutbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetOutbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetOutbox(ctx, req.(*GetOutboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetFollowers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetFollowers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetFollowers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetFollowers(ctx, req.(*GetFollowersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetFollowing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFollowingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetFollowing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetFollowing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetFollowing(ctx, req.(*GetFollowingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_GetLiked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).GetLiked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_GetLiked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).GetLiked(ctx, req.(*GetLikedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_SendActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).SendActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_SendActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).SendActivity(ctx, req.(*SendActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_ReceiveActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).ReceiveActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_ReceiveActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).ReceiveActivity(ctx, req.(*ReceiveActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacadeService_ForwardActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacadeServiceServer).ForwardActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FacadeService_ForwardActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacadeServiceServer).ForwardActivity(ctx, req.(*ForwardActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FacadeService_ServiceDesc is the grpc.ServiceDesc for FacadeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FacadeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peers_touch.touch.v1.actor.FacadeService",
	HandlerType: (*FacadeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateActor",
			Handler:    _FacadeService_CreateActor_Handler,
		},
		{
			MethodName: "GetActor",
			Handler:    _FacadeService_GetActor_Handler,
		},
		{
			MethodName: "UpdateActor",
			Handler:    _FacadeService_UpdateActor_Handler,
		},
		{
			MethodName: "DeleteActor",
			Handler:    _FacadeService_DeleteActor_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _FacadeService_Follow_Handler,
		},
		{
			MethodName: "Unfollow",
			Handler:    _FacadeService_Unfollow_Handler,
		},
		{
			MethodName: "CreateActivity",
			Handler:    _FacadeService_CreateActivity_Handler,
		},
		{
			MethodName: "GetActivity",
			Handler:    _FacadeService_GetActivity_Handler,
		},
		{
			MethodName: "DeleteActivity",
			Handler:    _FacadeService_DeleteActivity_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _FacadeService_Like_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _FacadeService_Unlike_Handler,
		},
		{
			MethodName: "Announce",
			Handler:    _FacadeService_Announce_Handler,
		},
		{
			MethodName: "GetInbox",
			Handler:    _FacadeService_GetInbox_Handler,
		},
		{
			MethodName: "GetOutbox",
			Handler:    _FacadeService_GetOutbox_Handler,
		},
		{
			MethodName: "GetFollowers",
			Handler:    _FacadeService_GetFollowers_Handler,
		},
		{
			MethodName: "GetFollowing",
			Handler:    _FacadeService_GetFollowing_Handler,
		},
		{
			MethodName: "GetLiked",
			Handler:    _FacadeService_GetLiked_Handler,
		},
		{
			MethodName: "SendActivity",
			Handler:    _FacadeService_SendActivity_Handler,
		},
		{
			MethodName: "ReceiveActivity",
			Handler:    _FacadeService_ReceiveActivity_Handler,
		},
		{
			MethodName: "ForwardActivity",
			Handler:    _FacadeService_ForwardActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "touch/v1/actor/facade.proto",
}
