// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/actor/follow.proto

package actorv1

import (
	v1 "github.com/peers-touch/peers-touch/proto/gen/touch/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Follow relationship
type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                      // Follow relationship ID
	FollowerId    string                 `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`    // Follower ID
	FollowingId   string                 `protobuf:"bytes,3,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // Following ID
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`       // Creation time
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                              // Status (pending, accepted, rejected)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_touch_v1_actor_follow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_follow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_follow_proto_rawDescGZIP(), []int{0}
}

func (x *Follow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Follow) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *Follow) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

func (x *Follow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Follow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Follow parameters
type FollowParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingId   string                 `protobuf:"bytes,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // Actor ID to follow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowParams) Reset() {
	*x = FollowParams{}
	mi := &file_touch_v1_actor_follow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowParams) ProtoMessage() {}

func (x *FollowParams) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_follow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowParams.ProtoReflect.Descriptor instead.
func (*FollowParams) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowParams) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

// Unfollow parameters
type UnfollowParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowingId   string                 `protobuf:"bytes,1,opt,name=following_id,json=followingId,proto3" json:"following_id,omitempty"` // Actor ID to unfollow
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowParams) Reset() {
	*x = UnfollowParams{}
	mi := &file_touch_v1_actor_follow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowParams) ProtoMessage() {}

func (x *UnfollowParams) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_follow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowParams.ProtoReflect.Descriptor instead.
func (*UnfollowParams) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_follow_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowParams) GetFollowingId() string {
	if x != nil {
		return x.FollowingId
	}
	return ""
}

// Follow list response
type FollowListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follows       []*Follow              `protobuf:"bytes,1,rep,name=follows,proto3" json:"follows,omitempty"`       // Follow list
	Pagination    *v1.PaginationInfo     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // Pagination information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListResponse) Reset() {
	*x = FollowListResponse{}
	mi := &file_touch_v1_actor_follow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListResponse) ProtoMessage() {}

func (x *FollowListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_follow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListResponse.ProtoReflect.Descriptor instead.
func (*FollowListResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_follow_proto_rawDescGZIP(), []int{3}
}

func (x *FollowListResponse) GetFollows() []*Follow {
	if x != nil {
		return x.Follows
	}
	return nil
}

func (x *FollowListResponse) GetPagination() *v1.PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_touch_v1_actor_follow_proto protoreflect.FileDescriptor

const file_touch_v1_actor_follow_proto_rawDesc = "" +
	"\n" +
	"\x1btouch/v1/actor/follow.proto\x12\x1apeers_touch.touch.v1.actor\x1a\x14touch/v1/types.proto\"\x93\x01\n" +
	"\x06Follow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\x12!\n" +
	"\ffollowing_id\x18\x03 \x01(\tR\vfollowingId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"1\n" +
	"\fFollowParams\x12!\n" +
	"\ffollowing_id\x18\x01 \x01(\tR\vfollowingId\"3\n" +
	"\x0eUnfollowParams\x12!\n" +
	"\ffollowing_id\x18\x01 \x01(\tR\vfollowingId\"\x98\x01\n" +
	"\x12FollowListResponse\x12<\n" +
	"\afollows\x18\x01 \x03(\v2\".peers_touch.touch.v1.actor.FollowR\afollows\x12D\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2$.peers_touch.touch.v1.PaginationInfoR\n" +
	"pagination2\x9d\x03\n" +
	"\rFollowService\x12[\n" +
	"\vFollowActor\x12(.peers_touch.touch.v1.actor.FollowParams\x1a\".peers_touch.touch.v1.actor.Follow\x12X\n" +
	"\rUnfollowActor\x12*.peers_touch.touch.v1.actor.UnfollowParams\x1a\x1b.peers_touch.touch.v1.Empty\x12j\n" +
	"\x10GetFollowingList\x12&.peers_touch.touch.v1.PaginationParams\x1a..peers_touch.touch.v1.actor.FollowListResponse\x12i\n" +
	"\x0fGetFollowerList\x12&.peers_touch.touch.v1.PaginationParams\x1a..peers_touch.touch.v1.actor.FollowListResponseBEZCgithub.com/peers-touch/peers-touch/proto/gen/touch/v1/actor;actorv1b\x06proto3"

var (
	file_touch_v1_actor_follow_proto_rawDescOnce sync.Once
	file_touch_v1_actor_follow_proto_rawDescData []byte
)

func file_touch_v1_actor_follow_proto_rawDescGZIP() []byte {
	file_touch_v1_actor_follow_proto_rawDescOnce.Do(func() {
		file_touch_v1_actor_follow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_actor_follow_proto_rawDesc), len(file_touch_v1_actor_follow_proto_rawDesc)))
	})
	return file_touch_v1_actor_follow_proto_rawDescData
}

var file_touch_v1_actor_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_touch_v1_actor_follow_proto_goTypes = []any{
	(*Follow)(nil),              // 0: peers_touch.touch.v1.actor.Follow
	(*FollowParams)(nil),        // 1: peers_touch.touch.v1.actor.FollowParams
	(*UnfollowParams)(nil),      // 2: peers_touch.touch.v1.actor.UnfollowParams
	(*FollowListResponse)(nil),  // 3: peers_touch.touch.v1.actor.FollowListResponse
	(*v1.PaginationInfo)(nil),   // 4: peers_touch.touch.v1.PaginationInfo
	(*v1.PaginationParams)(nil), // 5: peers_touch.touch.v1.PaginationParams
	(*v1.Empty)(nil),            // 6: peers_touch.touch.v1.Empty
}
var file_touch_v1_actor_follow_proto_depIdxs = []int32{
	0, // 0: peers_touch.touch.v1.actor.FollowListResponse.follows:type_name -> peers_touch.touch.v1.actor.Follow
	4, // 1: peers_touch.touch.v1.actor.FollowListResponse.pagination:type_name -> peers_touch.touch.v1.PaginationInfo
	1, // 2: peers_touch.touch.v1.actor.FollowService.FollowActor:input_type -> peers_touch.touch.v1.actor.FollowParams
	2, // 3: peers_touch.touch.v1.actor.FollowService.UnfollowActor:input_type -> peers_touch.touch.v1.actor.UnfollowParams
	5, // 4: peers_touch.touch.v1.actor.FollowService.GetFollowingList:input_type -> peers_touch.touch.v1.PaginationParams
	5, // 5: peers_touch.touch.v1.actor.FollowService.GetFollowerList:input_type -> peers_touch.touch.v1.PaginationParams
	0, // 6: peers_touch.touch.v1.actor.FollowService.FollowActor:output_type -> peers_touch.touch.v1.actor.Follow
	6, // 7: peers_touch.touch.v1.actor.FollowService.UnfollowActor:output_type -> peers_touch.touch.v1.Empty
	3, // 8: peers_touch.touch.v1.actor.FollowService.GetFollowingList:output_type -> peers_touch.touch.v1.actor.FollowListResponse
	3, // 9: peers_touch.touch.v1.actor.FollowService.GetFollowerList:output_type -> peers_touch.touch.v1.actor.FollowListResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_touch_v1_actor_follow_proto_init() }
func file_touch_v1_actor_follow_proto_init() {
	if File_touch_v1_actor_follow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_actor_follow_proto_rawDesc), len(file_touch_v1_actor_follow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_v1_actor_follow_proto_goTypes,
		DependencyIndexes: file_touch_v1_actor_follow_proto_depIdxs,
		MessageInfos:      file_touch_v1_actor_follow_proto_msgTypes,
	}.Build()
	File_touch_v1_actor_follow_proto = out.File
	file_touch_v1_actor_follow_proto_goTypes = nil
	file_touch_v1_actor_follow_proto_depIdxs = nil
}
