// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: touch/v1/actor/follow.proto

package actorv1

import (
	context "context"
	v1 "github.com/peers-touch/peers-touch/proto/gen/touch/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FollowService_FollowActor_FullMethodName      = "/peers_touch.touch.v1.actor.FollowService/FollowActor"
	FollowService_UnfollowActor_FullMethodName    = "/peers_touch.touch.v1.actor.FollowService/UnfollowActor"
	FollowService_GetFollowingList_FullMethodName = "/peers_touch.touch.v1.actor.FollowService/GetFollowingList"
	FollowService_GetFollowerList_FullMethodName  = "/peers_touch.touch.v1.actor.FollowService/GetFollowerList"
)

// FollowServiceClient is the client API for FollowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Follow service definition
type FollowServiceClient interface {
	// Follow actor
	FollowActor(ctx context.Context, in *FollowParams, opts ...grpc.CallOption) (*Follow, error)
	// Unfollow actor
	UnfollowActor(ctx context.Context, in *UnfollowParams, opts ...grpc.CallOption) (*v1.Empty, error)
	// Get following list
	GetFollowingList(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*FollowListResponse, error)
	// Get follower list
	GetFollowerList(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*FollowListResponse, error)
}

type followServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowServiceClient(cc grpc.ClientConnInterface) FollowServiceClient {
	return &followServiceClient{cc}
}

func (c *followServiceClient) FollowActor(ctx context.Context, in *FollowParams, opts ...grpc.CallOption) (*Follow, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Follow)
	err := c.cc.Invoke(ctx, FollowService_FollowActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) UnfollowActor(ctx context.Context, in *UnfollowParams, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, FollowService_UnfollowActor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowingList(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*FollowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowListResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *followServiceClient) GetFollowerList(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*FollowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowListResponse)
	err := c.cc.Invoke(ctx, FollowService_GetFollowerList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowServiceServer is the server API for FollowService service.
// All implementations must embed UnimplementedFollowServiceServer
// for forward compatibility.
//
// Follow service definition
type FollowServiceServer interface {
	// Follow actor
	FollowActor(context.Context, *FollowParams) (*Follow, error)
	// Unfollow actor
	UnfollowActor(context.Context, *UnfollowParams) (*v1.Empty, error)
	// Get following list
	GetFollowingList(context.Context, *v1.PaginationParams) (*FollowListResponse, error)
	// Get follower list
	GetFollowerList(context.Context, *v1.PaginationParams) (*FollowListResponse, error)
	mustEmbedUnimplementedFollowServiceServer()
}

// UnimplementedFollowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFollowServiceServer struct{}

func (UnimplementedFollowServiceServer) FollowActor(context.Context, *FollowParams) (*Follow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FollowActor not implemented")
}
func (UnimplementedFollowServiceServer) UnfollowActor(context.Context, *UnfollowParams) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnfollowActor not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowingList(context.Context, *v1.PaginationParams) (*FollowListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowingList not implemented")
}
func (UnimplementedFollowServiceServer) GetFollowerList(context.Context, *v1.PaginationParams) (*FollowListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowerList not implemented")
}
func (UnimplementedFollowServiceServer) mustEmbedUnimplementedFollowServiceServer() {}
func (UnimplementedFollowServiceServer) testEmbeddedByValue()                       {}

// UnsafeFollowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowServiceServer will
// result in compilation errors.
type UnsafeFollowServiceServer interface {
	mustEmbedUnimplementedFollowServiceServer()
}

func RegisterFollowServiceServer(s grpc.ServiceRegistrar, srv FollowServiceServer) {
	// If the following call pancis, it indicates UnimplementedFollowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FollowService_ServiceDesc, srv)
}

func _FollowService_FollowActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).FollowActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_FollowActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).FollowActor(ctx, req.(*FollowParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_UnfollowActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).UnfollowActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_UnfollowActor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).UnfollowActor(ctx, req.(*UnfollowParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PaginationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowingList(ctx, req.(*v1.PaginationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _FollowService_GetFollowerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PaginationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowServiceServer).GetFollowerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FollowService_GetFollowerList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowServiceServer).GetFollowerList(ctx, req.(*v1.PaginationParams))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowService_ServiceDesc is the grpc.ServiceDesc for FollowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peers_touch.touch.v1.actor.FollowService",
	HandlerType: (*FollowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FollowActor",
			Handler:    _FollowService_FollowActor_Handler,
		},
		{
			MethodName: "UnfollowActor",
			Handler:    _FollowService_UnfollowActor_Handler,
		},
		{
			MethodName: "GetFollowingList",
			Handler:    _FollowService_GetFollowingList_Handler,
		},
		{
			MethodName: "GetFollowerList",
			Handler:    _FollowService_GetFollowerList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "touch/v1/actor/follow.proto",
}
