// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: touch/v1/actor/inbox.proto

package actorv1

import (
	context "context"
	v1 "github.com/peers-touch/peers-touch/proto/gen/touch/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InboxService_GetInboxMessages_FullMethodName    = "/peers_touch.touch.v1.actor.InboxService/GetInboxMessages"
	InboxService_MarkMessagesAsRead_FullMethodName  = "/peers_touch.touch.v1.actor.InboxService/MarkMessagesAsRead"
	InboxService_DeleteInboxMessages_FullMethodName = "/peers_touch.touch.v1.actor.InboxService/DeleteInboxMessages"
)

// InboxServiceClient is the client API for InboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inbox service definition
type InboxServiceClient interface {
	// Get inbox messages list
	GetInboxMessages(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*InboxListResponse, error)
	// Mark messages as read
	MarkMessagesAsRead(ctx context.Context, in *MarkAsReadParams, opts ...grpc.CallOption) (*v1.Empty, error)
	// Delete inbox messages
	DeleteInboxMessages(ctx context.Context, in *MarkAsReadParams, opts ...grpc.CallOption) (*v1.Empty, error)
}

type inboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInboxServiceClient(cc grpc.ClientConnInterface) InboxServiceClient {
	return &inboxServiceClient{cc}
}

func (c *inboxServiceClient) GetInboxMessages(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*InboxListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InboxListResponse)
	err := c.cc.Invoke(ctx, InboxService_GetInboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inboxServiceClient) MarkMessagesAsRead(ctx context.Context, in *MarkAsReadParams, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, InboxService_MarkMessagesAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inboxServiceClient) DeleteInboxMessages(ctx context.Context, in *MarkAsReadParams, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, InboxService_DeleteInboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InboxServiceServer is the server API for InboxService service.
// All implementations must embed UnimplementedInboxServiceServer
// for forward compatibility.
//
// Inbox service definition
type InboxServiceServer interface {
	// Get inbox messages list
	GetInboxMessages(context.Context, *v1.PaginationParams) (*InboxListResponse, error)
	// Mark messages as read
	MarkMessagesAsRead(context.Context, *MarkAsReadParams) (*v1.Empty, error)
	// Delete inbox messages
	DeleteInboxMessages(context.Context, *MarkAsReadParams) (*v1.Empty, error)
	mustEmbedUnimplementedInboxServiceServer()
}

// UnimplementedInboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInboxServiceServer struct{}

func (UnimplementedInboxServiceServer) GetInboxMessages(context.Context, *v1.PaginationParams) (*InboxListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInboxMessages not implemented")
}
func (UnimplementedInboxServiceServer) MarkMessagesAsRead(context.Context, *MarkAsReadParams) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMessagesAsRead not implemented")
}
func (UnimplementedInboxServiceServer) DeleteInboxMessages(context.Context, *MarkAsReadParams) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInboxMessages not implemented")
}
func (UnimplementedInboxServiceServer) mustEmbedUnimplementedInboxServiceServer() {}
func (UnimplementedInboxServiceServer) testEmbeddedByValue()                      {}

// UnsafeInboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InboxServiceServer will
// result in compilation errors.
type UnsafeInboxServiceServer interface {
	mustEmbedUnimplementedInboxServiceServer()
}

func RegisterInboxServiceServer(s grpc.ServiceRegistrar, srv InboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedInboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InboxService_ServiceDesc, srv)
}

func _InboxService_GetInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PaginationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboxServiceServer).GetInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InboxService_GetInboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboxServiceServer).GetInboxMessages(ctx, req.(*v1.PaginationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _InboxService_MarkMessagesAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsReadParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboxServiceServer).MarkMessagesAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InboxService_MarkMessagesAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboxServiceServer).MarkMessagesAsRead(ctx, req.(*MarkAsReadParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _InboxService_DeleteInboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsReadParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InboxServiceServer).DeleteInboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InboxService_DeleteInboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InboxServiceServer).DeleteInboxMessages(ctx, req.(*MarkAsReadParams))
	}
	return interceptor(ctx, in, info, handler)
}

// InboxService_ServiceDesc is the grpc.ServiceDesc for InboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peers_touch.touch.v1.actor.InboxService",
	HandlerType: (*InboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInboxMessages",
			Handler:    _InboxService_GetInboxMessages_Handler,
		},
		{
			MethodName: "MarkMessagesAsRead",
			Handler:    _InboxService_MarkMessagesAsRead_Handler,
		},
		{
			MethodName: "DeleteInboxMessages",
			Handler:    _InboxService_DeleteInboxMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "touch/v1/actor/inbox.proto",
}
