// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/actor/options.proto

package actorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Actor options configuration
type ActorOptions struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Peers         *ActorOptions_PeersConfig `protobuf:"bytes,1,opt,name=peers,proto3" json:"peers,omitempty"` // Peers configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorOptions) Reset() {
	*x = ActorOptions{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorOptions) ProtoMessage() {}

func (x *ActorOptions) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorOptions.ProtoReflect.Descriptor instead.
func (*ActorOptions) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{0}
}

func (x *ActorOptions) GetPeers() *ActorOptions_PeersConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Get actor options request
type GetActorOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActorOptionsRequest) Reset() {
	*x = GetActorOptionsRequest{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActorOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActorOptionsRequest) ProtoMessage() {}

func (x *GetActorOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActorOptionsRequest.ProtoReflect.Descriptor instead.
func (*GetActorOptionsRequest) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{1}
}

// Update actor options request
type UpdateActorOptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       *ActorOptions          `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"` // Actor options to update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateActorOptionsRequest) Reset() {
	*x = UpdateActorOptionsRequest{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActorOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActorOptionsRequest) ProtoMessage() {}

func (x *UpdateActorOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActorOptionsRequest.ProtoReflect.Descriptor instead.
func (*UpdateActorOptionsRequest) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateActorOptionsRequest) GetOptions() *ActorOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Person configuration
type ActorOptions_PersonConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // Person name
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"` // Person email
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorOptions_PersonConfig) Reset() {
	*x = ActorOptions_PersonConfig{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorOptions_PersonConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorOptions_PersonConfig) ProtoMessage() {}

func (x *ActorOptions_PersonConfig) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorOptions_PersonConfig.ProtoReflect.Descriptor instead.
func (*ActorOptions_PersonConfig) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ActorOptions_PersonConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActorOptions_PersonConfig) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Actor configuration
type ActorOptions_ActorConfig struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Person        []*ActorOptions_PersonConfig `protobuf:"bytes,1,rep,name=person,proto3" json:"person,omitempty"` // List of persons
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorOptions_ActorConfig) Reset() {
	*x = ActorOptions_ActorConfig{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorOptions_ActorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorOptions_ActorConfig) ProtoMessage() {}

func (x *ActorOptions_ActorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorOptions_ActorConfig.ProtoReflect.Descriptor instead.
func (*ActorOptions_ActorConfig) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ActorOptions_ActorConfig) GetPerson() []*ActorOptions_PersonConfig {
	if x != nil {
		return x.Person
	}
	return nil
}

// Peers configuration
type ActorOptions_PeersConfig struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Actor         *ActorOptions_ActorConfig `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"` // Actor configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorOptions_PeersConfig) Reset() {
	*x = ActorOptions_PeersConfig{}
	mi := &file_touch_v1_actor_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorOptions_PeersConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorOptions_PeersConfig) ProtoMessage() {}

func (x *ActorOptions_PeersConfig) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_actor_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorOptions_PeersConfig.ProtoReflect.Descriptor instead.
func (*ActorOptions_PeersConfig) Descriptor() ([]byte, []int) {
	return file_touch_v1_actor_options_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ActorOptions_PeersConfig) GetActor() *ActorOptions_ActorConfig {
	if x != nil {
		return x.Actor
	}
	return nil
}

var File_touch_v1_actor_options_proto protoreflect.FileDescriptor

const file_touch_v1_actor_options_proto_rawDesc = "" +
	"\n" +
	"\x1ctouch/v1/actor/options.proto\x12\x1apeers_touch.touch.v1.actor\"\xcd\x02\n" +
	"\fActorOptions\x12J\n" +
	"\x05peers\x18\x01 \x01(\v24.peers_touch.touch.v1.actor.ActorOptions.PeersConfigR\x05peers\x1a8\n" +
	"\fPersonConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x1a\\\n" +
	"\vActorConfig\x12M\n" +
	"\x06person\x18\x01 \x03(\v25.peers_touch.touch.v1.actor.ActorOptions.PersonConfigR\x06person\x1aY\n" +
	"\vPeersConfig\x12J\n" +
	"\x05actor\x18\x01 \x01(\v24.peers_touch.touch.v1.actor.ActorOptions.ActorConfigR\x05actor\"\x18\n" +
	"\x16GetActorOptionsRequest\"_\n" +
	"\x19UpdateActorOptionsRequest\x12B\n" +
	"\aoptions\x18\x01 \x01(\v2(.peers_touch.touch.v1.actor.ActorOptionsR\aoptions2\xfd\x01\n" +
	"\x13ActorOptionsService\x12o\n" +
	"\x0fGetActorOptions\x122.peers_touch.touch.v1.actor.GetActorOptionsRequest\x1a(.peers_touch.touch.v1.actor.ActorOptions\x12u\n" +
	"\x12UpdateActorOptions\x125.peers_touch.touch.v1.actor.UpdateActorOptionsRequest\x1a(.peers_touch.touch.v1.actor.ActorOptionsBEZCgithub.com/peers-touch/peers-touch/proto/gen/touch/v1/actor;actorv1b\x06proto3"

var (
	file_touch_v1_actor_options_proto_rawDescOnce sync.Once
	file_touch_v1_actor_options_proto_rawDescData []byte
)

func file_touch_v1_actor_options_proto_rawDescGZIP() []byte {
	file_touch_v1_actor_options_proto_rawDescOnce.Do(func() {
		file_touch_v1_actor_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_actor_options_proto_rawDesc), len(file_touch_v1_actor_options_proto_rawDesc)))
	})
	return file_touch_v1_actor_options_proto_rawDescData
}

var file_touch_v1_actor_options_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_touch_v1_actor_options_proto_goTypes = []any{
	(*ActorOptions)(nil),              // 0: peers_touch.touch.v1.actor.ActorOptions
	(*GetActorOptionsRequest)(nil),    // 1: peers_touch.touch.v1.actor.GetActorOptionsRequest
	(*UpdateActorOptionsRequest)(nil), // 2: peers_touch.touch.v1.actor.UpdateActorOptionsRequest
	(*ActorOptions_PersonConfig)(nil), // 3: peers_touch.touch.v1.actor.ActorOptions.PersonConfig
	(*ActorOptions_ActorConfig)(nil),  // 4: peers_touch.touch.v1.actor.ActorOptions.ActorConfig
	(*ActorOptions_PeersConfig)(nil),  // 5: peers_touch.touch.v1.actor.ActorOptions.PeersConfig
}
var file_touch_v1_actor_options_proto_depIdxs = []int32{
	5, // 0: peers_touch.touch.v1.actor.ActorOptions.peers:type_name -> peers_touch.touch.v1.actor.ActorOptions.PeersConfig
	0, // 1: peers_touch.touch.v1.actor.UpdateActorOptionsRequest.options:type_name -> peers_touch.touch.v1.actor.ActorOptions
	3, // 2: peers_touch.touch.v1.actor.ActorOptions.ActorConfig.person:type_name -> peers_touch.touch.v1.actor.ActorOptions.PersonConfig
	4, // 3: peers_touch.touch.v1.actor.ActorOptions.PeersConfig.actor:type_name -> peers_touch.touch.v1.actor.ActorOptions.ActorConfig
	1, // 4: peers_touch.touch.v1.actor.ActorOptionsService.GetActorOptions:input_type -> peers_touch.touch.v1.actor.GetActorOptionsRequest
	2, // 5: peers_touch.touch.v1.actor.ActorOptionsService.UpdateActorOptions:input_type -> peers_touch.touch.v1.actor.UpdateActorOptionsRequest
	0, // 6: peers_touch.touch.v1.actor.ActorOptionsService.GetActorOptions:output_type -> peers_touch.touch.v1.actor.ActorOptions
	0, // 7: peers_touch.touch.v1.actor.ActorOptionsService.UpdateActorOptions:output_type -> peers_touch.touch.v1.actor.ActorOptions
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_touch_v1_actor_options_proto_init() }
func file_touch_v1_actor_options_proto_init() {
	if File_touch_v1_actor_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_actor_options_proto_rawDesc), len(file_touch_v1_actor_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_v1_actor_options_proto_goTypes,
		DependencyIndexes: file_touch_v1_actor_options_proto_depIdxs,
		MessageInfos:      file_touch_v1_actor_options_proto_msgTypes,
	}.Build()
	File_touch_v1_actor_options_proto = out.File
	file_touch_v1_actor_options_proto_goTypes = nil
	file_touch_v1_actor_options_proto_depIdxs = nil
}
