// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: touch/v1/actor/outbox.proto

package actorv1

import (
	context "context"
	v1 "github.com/peers-touch/peers-touch/proto/gen/touch/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OutboxService_SendMessage_FullMethodName         = "/peers_touch.touch.v1.actor.OutboxService/SendMessage"
	OutboxService_GetOutboxMessages_FullMethodName   = "/peers_touch.touch.v1.actor.OutboxService/GetOutboxMessages"
	OutboxService_DeleteOutboxMessage_FullMethodName = "/peers_touch.touch.v1.actor.OutboxService/DeleteOutboxMessage"
)

// OutboxServiceClient is the client API for OutboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Outbox service definition
type OutboxServiceClient interface {
	// Send message
	SendMessage(ctx context.Context, in *SendMessageParams, opts ...grpc.CallOption) (*OutboxMessage, error)
	// Get outbox messages list
	GetOutboxMessages(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*OutboxListResponse, error)
	// Delete outbox message
	DeleteOutboxMessage(ctx context.Context, in *v1.IDParams, opts ...grpc.CallOption) (*v1.Empty, error)
}

type outboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOutboxServiceClient(cc grpc.ClientConnInterface) OutboxServiceClient {
	return &outboxServiceClient{cc}
}

func (c *outboxServiceClient) SendMessage(ctx context.Context, in *SendMessageParams, opts ...grpc.CallOption) (*OutboxMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutboxMessage)
	err := c.cc.Invoke(ctx, OutboxService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboxServiceClient) GetOutboxMessages(ctx context.Context, in *v1.PaginationParams, opts ...grpc.CallOption) (*OutboxListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutboxListResponse)
	err := c.cc.Invoke(ctx, OutboxService_GetOutboxMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *outboxServiceClient) DeleteOutboxMessage(ctx context.Context, in *v1.IDParams, opts ...grpc.CallOption) (*v1.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.Empty)
	err := c.cc.Invoke(ctx, OutboxService_DeleteOutboxMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutboxServiceServer is the server API for OutboxService service.
// All implementations must embed UnimplementedOutboxServiceServer
// for forward compatibility.
//
// Outbox service definition
type OutboxServiceServer interface {
	// Send message
	SendMessage(context.Context, *SendMessageParams) (*OutboxMessage, error)
	// Get outbox messages list
	GetOutboxMessages(context.Context, *v1.PaginationParams) (*OutboxListResponse, error)
	// Delete outbox message
	DeleteOutboxMessage(context.Context, *v1.IDParams) (*v1.Empty, error)
	mustEmbedUnimplementedOutboxServiceServer()
}

// UnimplementedOutboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOutboxServiceServer struct{}

func (UnimplementedOutboxServiceServer) SendMessage(context.Context, *SendMessageParams) (*OutboxMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedOutboxServiceServer) GetOutboxMessages(context.Context, *v1.PaginationParams) (*OutboxListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOutboxMessages not implemented")
}
func (UnimplementedOutboxServiceServer) DeleteOutboxMessage(context.Context, *v1.IDParams) (*v1.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOutboxMessage not implemented")
}
func (UnimplementedOutboxServiceServer) mustEmbedUnimplementedOutboxServiceServer() {}
func (UnimplementedOutboxServiceServer) testEmbeddedByValue()                       {}

// UnsafeOutboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OutboxServiceServer will
// result in compilation errors.
type UnsafeOutboxServiceServer interface {
	mustEmbedUnimplementedOutboxServiceServer()
}

func RegisterOutboxServiceServer(s grpc.ServiceRegistrar, srv OutboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedOutboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OutboxService_ServiceDesc, srv)
}

func _OutboxService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxServiceServer).SendMessage(ctx, req.(*SendMessageParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboxService_GetOutboxMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PaginationParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxServiceServer).GetOutboxMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxService_GetOutboxMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxServiceServer).GetOutboxMessages(ctx, req.(*v1.PaginationParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _OutboxService_DeleteOutboxMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.IDParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutboxServiceServer).DeleteOutboxMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OutboxService_DeleteOutboxMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutboxServiceServer).DeleteOutboxMessage(ctx, req.(*v1.IDParams))
	}
	return interceptor(ctx, in, info, handler)
}

// OutboxService_ServiceDesc is the grpc.ServiceDesc for OutboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OutboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "peers_touch.touch.v1.actor.OutboxService",
	HandlerType: (*OutboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _OutboxService_SendMessage_Handler,
		},
		{
			MethodName: "GetOutboxMessages",
			Handler:    _OutboxService_GetOutboxMessages_Handler,
		},
		{
			MethodName: "DeleteOutboxMessage",
			Handler:    _OutboxService_DeleteOutboxMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "touch/v1/actor/outbox.proto",
}
