// PEERS_GENERATION_CONFIG:
//   targets: [backend]
//   model_only: true

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: v1/peers_touch_station/ai_box/provider.proto

package ai_box

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AI服务提供商
type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // 提供商ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 提供商名称 (如: openai, anthropic)
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`                         // 是否启用
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                  // 描述信息
	Logo          string                 `protobuf:"bytes,5,opt,name=logo,proto3" json:"logo,omitempty"`                                // Logo URL或base64
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`                               // 排序权重
	CheckModel    string                 `protobuf:"bytes,7,opt,name=check_model,json=checkModel,proto3" json:"check_model,omitempty"`  // 检测模型
	SourceType    string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`  // 源类型
	KeyVaults     string                 `protobuf:"bytes,9,opt,name=key_vaults,json=keyVaults,proto3" json:"key_vaults,omitempty"`     // 密钥配置 (JSON字符串)
	Settings      string                 `protobuf:"bytes,10,opt,name=settings,proto3" json:"settings,omitempty"`                       // 设置配置 (JSON字符串)
	Config        string                 `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`                           // 扩展配置 (JSON字符串)
	AccessedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=accessed_at,json=accessedAt,proto3" json:"accessed_at,omitempty"` // 访问时间
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 创建时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Provider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Provider) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *Provider) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *Provider) GetCheckModel() string {
	if x != nil {
		return x.CheckModel
	}
	return ""
}

func (x *Provider) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Provider) GetKeyVaults() string {
	if x != nil {
		return x.KeyVaults
	}
	return ""
}

func (x *Provider) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *Provider) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *Provider) GetAccessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AccessedAt
	}
	return nil
}

func (x *Provider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Provider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// 创建提供商请求
type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // 提供商名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`                 // 描述信息
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`                               // Logo URL或base64
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`                              // 排序权重
	CheckModel    string                 `protobuf:"bytes,5,opt,name=check_model,json=checkModel,proto3" json:"check_model,omitempty"` // 检测模型
	SourceType    string                 `protobuf:"bytes,6,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // 源类型
	KeyVaults     string                 `protobuf:"bytes,7,opt,name=key_vaults,json=keyVaults,proto3" json:"key_vaults,omitempty"`    // 密钥配置 (JSON字符串)
	Settings      string                 `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty"`                       // 设置配置 (JSON字符串)
	Config        string                 `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`                           // 扩展配置 (JSON字符串)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProviderRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *CreateProviderRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateProviderRequest) GetCheckModel() string {
	if x != nil {
		return x.CheckModel
	}
	return ""
}

func (x *CreateProviderRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CreateProviderRequest) GetKeyVaults() string {
	if x != nil {
		return x.KeyVaults
	}
	return ""
}

func (x *CreateProviderRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *CreateProviderRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// 创建提供商响应
type CreateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // 创建的提供商
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// 更新提供商请求
type UpdateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 提供商ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // 提供商名称
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                 // 描述信息
	Logo          string                 `protobuf:"bytes,4,opt,name=logo,proto3" json:"logo,omitempty"`                               // Logo URL或base64
	Sort          int32                  `protobuf:"varint,5,opt,name=sort,proto3" json:"sort,omitempty"`                              // 排序权重
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`                        // 是否启用
	CheckModel    string                 `protobuf:"bytes,7,opt,name=check_model,json=checkModel,proto3" json:"check_model,omitempty"` // 检测模型
	SourceType    string                 `protobuf:"bytes,8,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // 源类型
	KeyVaults     string                 `protobuf:"bytes,9,opt,name=key_vaults,json=keyVaults,proto3" json:"key_vaults,omitempty"`    // 密钥配置 (JSON字符串)
	Settings      string                 `protobuf:"bytes,10,opt,name=settings,proto3" json:"settings,omitempty"`                      // 设置配置 (JSON字符串)
	Config        string                 `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`                          // 扩展配置 (JSON字符串)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderRequest) Reset() {
	*x = UpdateProviderRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderRequest) ProtoMessage() {}

func (x *UpdateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderRequest.ProtoReflect.Descriptor instead.
func (*UpdateProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProviderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProviderRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *UpdateProviderRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *UpdateProviderRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdateProviderRequest) GetCheckModel() string {
	if x != nil {
		return x.CheckModel
	}
	return ""
}

func (x *UpdateProviderRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *UpdateProviderRequest) GetKeyVaults() string {
	if x != nil {
		return x.KeyVaults
	}
	return ""
}

func (x *UpdateProviderRequest) GetSettings() string {
	if x != nil {
		return x.Settings
	}
	return ""
}

func (x *UpdateProviderRequest) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

// 更新提供商响应
type UpdateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // 更新的提供商
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProviderResponse) Reset() {
	*x = UpdateProviderResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProviderResponse) ProtoMessage() {}

func (x *UpdateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProviderResponse.ProtoReflect.Descriptor instead.
func (*UpdateProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// 删除提供商请求
type DeleteProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 提供商ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderRequest) Reset() {
	*x = DeleteProviderRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderRequest) ProtoMessage() {}

func (x *DeleteProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderRequest.ProtoReflect.Descriptor instead.
func (*DeleteProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 删除提供商响应
type DeleteProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProviderResponse) Reset() {
	*x = DeleteProviderResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProviderResponse) ProtoMessage() {}

func (x *DeleteProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProviderResponse.ProtoReflect.Descriptor instead.
func (*DeleteProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取提供商请求
type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 提供商ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{7}
}

func (x *GetProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取提供商响应
type GetProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // 提供商信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderResponse) Reset() {
	*x = GetProviderResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderResponse) ProtoMessage() {}

func (x *GetProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderResponse.ProtoReflect.Descriptor instead.
func (*GetProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{8}
}

func (x *GetProviderResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// 列出提供商请求
type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                  // 页码
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // 每页数量
	EnabledOnly   bool                   `protobuf:"varint,3,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"` // 只显示启用的
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{9}
}

func (x *ListProvidersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProvidersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListProvidersRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

// 列出提供商响应
type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`                // 提供商列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{10}
}

func (x *ListProvidersResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *ListProvidersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProvidersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProvidersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 测试提供商请求
type TestProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 提供商ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderRequest) Reset() {
	*x = TestProviderRequest{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderRequest) ProtoMessage() {}

func (x *TestProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderRequest.ProtoReflect.Descriptor instead.
func (*TestProviderRequest) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{11}
}

func (x *TestProviderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 测试提供商响应
type TestProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 测试消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderResponse) Reset() {
	*x = TestProviderResponse{}
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderResponse) ProtoMessage() {}

func (x *TestProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_peers_touch_station_ai_box_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderResponse.ProtoReflect.Descriptor instead.
func (*TestProviderResponse) Descriptor() ([]byte, []int) {
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP(), []int{12}
}

func (x *TestProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_v1_peers_touch_station_ai_box_provider_proto protoreflect.FileDescriptor

const file_v1_peers_touch_station_ai_box_provider_proto_rawDesc = "" +
	"\n" +
	",v1/peers_touch_station/ai_box/provider.proto\x12)peers_touch.v1.peers_touch_station.ai_box\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04logo\x18\x05 \x01(\tR\x04logo\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\x12\x1f\n" +
	"\vcheck_model\x18\a \x01(\tR\n" +
	"checkModel\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"key_vaults\x18\t \x01(\tR\tkeyVaults\x12\x1a\n" +
	"\bsettings\x18\n" +
	" \x01(\tR\bsettings\x12\x16\n" +
	"\x06config\x18\v \x01(\tR\x06config\x12;\n" +
	"\vaccessed_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"accessedAt\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8a\x02\n" +
	"\x15CreateProviderRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\x12\x1f\n" +
	"\vcheck_model\x18\x05 \x01(\tR\n" +
	"checkModel\x12\x1f\n" +
	"\vsource_type\x18\x06 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"key_vaults\x18\a \x01(\tR\tkeyVaults\x12\x1a\n" +
	"\bsettings\x18\b \x01(\tR\bsettings\x12\x16\n" +
	"\x06config\x18\t \x01(\tR\x06config\"i\n" +
	"\x16CreateProviderResponse\x12O\n" +
	"\bprovider\x18\x01 \x01(\v23.peers_touch.v1.peers_touch_station.ai_box.ProviderR\bprovider\"\xb4\x02\n" +
	"\x15UpdateProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04logo\x18\x04 \x01(\tR\x04logo\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\x05R\x04sort\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12\x1f\n" +
	"\vcheck_model\x18\a \x01(\tR\n" +
	"checkModel\x12\x1f\n" +
	"\vsource_type\x18\b \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"key_vaults\x18\t \x01(\tR\tkeyVaults\x12\x1a\n" +
	"\bsettings\x18\n" +
	" \x01(\tR\bsettings\x12\x16\n" +
	"\x06config\x18\v \x01(\tR\x06config\"i\n" +
	"\x16UpdateProviderResponse\x12O\n" +
	"\bprovider\x18\x01 \x01(\v23.peers_touch.v1.peers_touch_station.ai_box.ProviderR\bprovider\"'\n" +
	"\x15DeleteProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"$\n" +
	"\x12GetProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x13GetProviderResponse\x12O\n" +
	"\bprovider\x18\x01 \x01(\v23.peers_touch.v1.peers_touch_station.ai_box.ProviderR\bprovider\"j\n" +
	"\x14ListProvidersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fenabled_only\x18\x03 \x01(\bR\venabledOnly\"\xb1\x01\n" +
	"\x15ListProvidersResponse\x12Q\n" +
	"\tproviders\x18\x01 \x03(\v23.peers_touch.v1.peers_touch_station.ai_box.ProviderR\tproviders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"%\n" +
	"\x13TestProviderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14TestProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageBiZggithub.com/peers-touch/peers-touch/station/app/subserver/ai-box/proto_gen/v1/peers_touch_station/ai_boxb\x06proto3"

var (
	file_v1_peers_touch_station_ai_box_provider_proto_rawDescOnce sync.Once
	file_v1_peers_touch_station_ai_box_provider_proto_rawDescData []byte
)

func file_v1_peers_touch_station_ai_box_provider_proto_rawDescGZIP() []byte {
	file_v1_peers_touch_station_ai_box_provider_proto_rawDescOnce.Do(func() {
		file_v1_peers_touch_station_ai_box_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_peers_touch_station_ai_box_provider_proto_rawDesc), len(file_v1_peers_touch_station_ai_box_provider_proto_rawDesc)))
	})
	return file_v1_peers_touch_station_ai_box_provider_proto_rawDescData
}

var file_v1_peers_touch_station_ai_box_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_peers_touch_station_ai_box_provider_proto_goTypes = []any{
	(*Provider)(nil),               // 0: peers_touch.v1.peers_touch_station.ai_box.Provider
	(*CreateProviderRequest)(nil),  // 1: peers_touch.v1.peers_touch_station.ai_box.CreateProviderRequest
	(*CreateProviderResponse)(nil), // 2: peers_touch.v1.peers_touch_station.ai_box.CreateProviderResponse
	(*UpdateProviderRequest)(nil),  // 3: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderRequest
	(*UpdateProviderResponse)(nil), // 4: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderResponse
	(*DeleteProviderRequest)(nil),  // 5: peers_touch.v1.peers_touch_station.ai_box.DeleteProviderRequest
	(*DeleteProviderResponse)(nil), // 6: peers_touch.v1.peers_touch_station.ai_box.DeleteProviderResponse
	(*GetProviderRequest)(nil),     // 7: peers_touch.v1.peers_touch_station.ai_box.GetProviderRequest
	(*GetProviderResponse)(nil),    // 8: peers_touch.v1.peers_touch_station.ai_box.GetProviderResponse
	(*ListProvidersRequest)(nil),   // 9: peers_touch.v1.peers_touch_station.ai_box.ListProvidersRequest
	(*ListProvidersResponse)(nil),  // 10: peers_touch.v1.peers_touch_station.ai_box.ListProvidersResponse
	(*TestProviderRequest)(nil),    // 11: peers_touch.v1.peers_touch_station.ai_box.TestProviderRequest
	(*TestProviderResponse)(nil),   // 12: peers_touch.v1.peers_touch_station.ai_box.TestProviderResponse
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
}
var file_v1_peers_touch_station_ai_box_provider_proto_depIdxs = []int32{
	13, // 0: peers_touch.v1.peers_touch_station.ai_box.Provider.accessed_at:type_name -> google.protobuf.Timestamp
	13, // 1: peers_touch.v1.peers_touch_station.ai_box.Provider.created_at:type_name -> google.protobuf.Timestamp
	13, // 2: peers_touch.v1.peers_touch_station.ai_box.Provider.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: peers_touch.v1.peers_touch_station.ai_box.CreateProviderResponse.provider:type_name -> peers_touch.v1.peers_touch_station.ai_box.Provider
	0,  // 4: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderResponse.provider:type_name -> peers_touch.v1.peers_touch_station.ai_box.Provider
	0,  // 5: peers_touch.v1.peers_touch_station.ai_box.GetProviderResponse.provider:type_name -> peers_touch.v1.peers_touch_station.ai_box.Provider
	0,  // 6: peers_touch.v1.peers_touch_station.ai_box.ListProvidersResponse.providers:type_name -> peers_touch.v1.peers_touch_station.ai_box.Provider
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_v1_peers_touch_station_ai_box_provider_proto_init() }
func file_v1_peers_touch_station_ai_box_provider_proto_init() {
	if File_v1_peers_touch_station_ai_box_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_peers_touch_station_ai_box_provider_proto_rawDesc), len(file_v1_peers_touch_station_ai_box_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_peers_touch_station_ai_box_provider_proto_goTypes,
		DependencyIndexes: file_v1_peers_touch_station_ai_box_provider_proto_depIdxs,
		MessageInfos:      file_v1_peers_touch_station_ai_box_provider_proto_msgTypes,
	}.Build()
	File_v1_peers_touch_station_ai_box_provider_proto = out.File
	file_v1_peers_touch_station_ai_box_provider_proto_goTypes = nil
	file_v1_peers_touch_station_ai_box_provider_proto_depIdxs = nil
}
