// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/common.proto

package touchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common status codes
type StatusCode int32

const (
	StatusCode_STATUS_CODE_UNSPECIFIED    StatusCode = 0
	StatusCode_STATUS_CODE_SUCCESS        StatusCode = 200 // Success
	StatusCode_STATUS_CODE_BAD_REQUEST    StatusCode = 400 // Bad request
	StatusCode_STATUS_CODE_UNAUTHORIZED   StatusCode = 401 // Unauthorized
	StatusCode_STATUS_CODE_FORBIDDEN      StatusCode = 403 // Forbidden
	StatusCode_STATUS_CODE_NOT_FOUND      StatusCode = 404 // Not found
	StatusCode_STATUS_CODE_INTERNAL_ERROR StatusCode = 500 // Internal server error
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "STATUS_CODE_UNSPECIFIED",
		200: "STATUS_CODE_SUCCESS",
		400: "STATUS_CODE_BAD_REQUEST",
		401: "STATUS_CODE_UNAUTHORIZED",
		403: "STATUS_CODE_FORBIDDEN",
		404: "STATUS_CODE_NOT_FOUND",
		500: "STATUS_CODE_INTERNAL_ERROR",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSPECIFIED":    0,
		"STATUS_CODE_SUCCESS":        200,
		"STATUS_CODE_BAD_REQUEST":    400,
		"STATUS_CODE_UNAUTHORIZED":   401,
		"STATUS_CODE_FORBIDDEN":      403,
		"STATUS_CODE_NOT_FOUND":      404,
		"STATUS_CODE_INTERNAL_ERROR": 500,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_touch_v1_common_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_touch_v1_common_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_touch_v1_common_proto_rawDescGZIP(), []int{0}
}

// Success response structure
type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Status code
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`   // Message
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // Response data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_touch_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *SuccessResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SuccessResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SuccessResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// Paginated data structure
type PageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // Total count
	No            int32                  `protobuf:"varint,2,opt,name=no,proto3" json:"no,omitempty"`       // Page number
	List          []*anypb.Any           `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`    // Data list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageData) Reset() {
	*x = PageData{}
	mi := &file_touch_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageData) ProtoMessage() {}

func (x *PageData) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageData.ProtoReflect.Descriptor instead.
func (*PageData) Descriptor() ([]byte, []int) {
	return file_touch_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageData) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageData) GetNo() int32 {
	if x != nil {
		return x.No
	}
	return 0
}

func (x *PageData) GetList() []*anypb.Any {
	if x != nil {
		return x.List
	}
	return nil
}

// Generic paginated response
type PaginatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *SuccessResponse       `protobuf:"bytes,1,opt,name=success,proto3" json:"success,omitempty"`                   // Success response
	PageData      *PageData              `protobuf:"bytes,2,opt,name=page_data,json=pageData,proto3" json:"page_data,omitempty"` // Paginated data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginatedResponse) Reset() {
	*x = PaginatedResponse{}
	mi := &file_touch_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginatedResponse) ProtoMessage() {}

func (x *PaginatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginatedResponse.ProtoReflect.Descriptor instead.
func (*PaginatedResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *PaginatedResponse) GetSuccess() *SuccessResponse {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *PaginatedResponse) GetPageData() *PageData {
	if x != nil {
		return x.PageData
	}
	return nil
}

var File_touch_v1_common_proto protoreflect.FileDescriptor

const file_touch_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15touch/v1/common.proto\x12\x14peers_touch.touch.v1\x1a\x19google/protobuf/any.proto\"a\n" +
	"\x0fSuccessResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\"Z\n" +
	"\bPageData\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x0e\n" +
	"\x02no\x18\x02 \x01(\x05R\x02no\x12(\n" +
	"\x04list\x18\x03 \x03(\v2\x14.google.protobuf.AnyR\x04list\"\x91\x01\n" +
	"\x11PaginatedResponse\x12?\n" +
	"\asuccess\x18\x01 \x01(\v2%.peers_touch.touch.v1.SuccessResponseR\asuccess\x12;\n" +
	"\tpage_data\x18\x02 \x01(\v2\x1e.peers_touch.touch.v1.PageDataR\bpageData*\xd9\x01\n" +
	"\n" +
	"StatusCode\x12\x1b\n" +
	"\x17STATUS_CODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x13STATUS_CODE_SUCCESS\x10\xc8\x01\x12\x1c\n" +
	"\x17STATUS_CODE_BAD_REQUEST\x10\x90\x03\x12\x1d\n" +
	"\x18STATUS_CODE_UNAUTHORIZED\x10\x91\x03\x12\x1a\n" +
	"\x15STATUS_CODE_FORBIDDEN\x10\x93\x03\x12\x1a\n" +
	"\x15STATUS_CODE_NOT_FOUND\x10\x94\x03\x12\x1f\n" +
	"\x1aSTATUS_CODE_INTERNAL_ERROR\x10\xf4\x03B?Z=github.com/peers-touch/peers-touch/proto/gen/touch/v1;touchv1b\x06proto3"

var (
	file_touch_v1_common_proto_rawDescOnce sync.Once
	file_touch_v1_common_proto_rawDescData []byte
)

func file_touch_v1_common_proto_rawDescGZIP() []byte {
	file_touch_v1_common_proto_rawDescOnce.Do(func() {
		file_touch_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_common_proto_rawDesc), len(file_touch_v1_common_proto_rawDesc)))
	})
	return file_touch_v1_common_proto_rawDescData
}

var file_touch_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_touch_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_touch_v1_common_proto_goTypes = []any{
	(StatusCode)(0),           // 0: peers_touch.touch.v1.StatusCode
	(*SuccessResponse)(nil),   // 1: peers_touch.touch.v1.SuccessResponse
	(*PageData)(nil),          // 2: peers_touch.touch.v1.PageData
	(*PaginatedResponse)(nil), // 3: peers_touch.touch.v1.PaginatedResponse
	(*anypb.Any)(nil),         // 4: google.protobuf.Any
}
var file_touch_v1_common_proto_depIdxs = []int32{
	4, // 0: peers_touch.touch.v1.SuccessResponse.data:type_name -> google.protobuf.Any
	4, // 1: peers_touch.touch.v1.PageData.list:type_name -> google.protobuf.Any
	1, // 2: peers_touch.touch.v1.PaginatedResponse.success:type_name -> peers_touch.touch.v1.SuccessResponse
	2, // 3: peers_touch.touch.v1.PaginatedResponse.page_data:type_name -> peers_touch.touch.v1.PageData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_touch_v1_common_proto_init() }
func file_touch_v1_common_proto_init() {
	if File_touch_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_common_proto_rawDesc), len(file_touch_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_touch_v1_common_proto_goTypes,
		DependencyIndexes: file_touch_v1_common_proto_depIdxs,
		EnumInfos:         file_touch_v1_common_proto_enumTypes,
		MessageInfos:      file_touch_v1_common_proto_msgTypes,
	}.Build()
	File_touch_v1_common_proto = out.File
	file_touch_v1_common_proto_goTypes = nil
	file_touch_v1_common_proto_depIdxs = nil
}
