// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/errors.proto

package touchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common error codes for Touch module
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED ErrorCode = 0
	// Well-known errors
	ErrorCode_ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT ErrorCode = 10001 // Invalid resource format
	ErrorCode_ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE ErrorCode = 10002 // Unsupported prefix type
	// Actor errors
	ErrorCode_ERROR_CODE_ACTOR_INVALID_NAME        ErrorCode = 10003 // Invalid actor name
	ErrorCode_ERROR_CODE_ACTOR_INVALID_EMAIL       ErrorCode = 10004 // Invalid actor email
	ErrorCode_ERROR_CODE_ACTOR_INVALID_PASSWORD    ErrorCode = 10005 // Invalid actor password
	ErrorCode_ERROR_CODE_ACTOR_ACTOR_EXISTS        ErrorCode = 10006 // Actor already exists
	ErrorCode_ERROR_CODE_ACTOR_INVALID_PASSPORT    ErrorCode = 10007 // Invalid actor passport
	ErrorCode_ERROR_CODE_ACTOR_NOT_FOUND           ErrorCode = 10008 // Actor not found
	ErrorCode_ERROR_CODE_ACTOR_INVALID_CREDENTIALS ErrorCode = 10009 // Invalid credentials
	// Peer address errors
	ErrorCode_ERROR_CODE_PEER_ADDR_EXISTS ErrorCode = 10010 // Peer address already exists
	// Profile errors
	ErrorCode_ERROR_CODE_PROFILE_INVALID_GENDER       ErrorCode = 20001 // Invalid gender value
	ErrorCode_ERROR_CODE_PROFILE_INVALID_EMAIL_FORMAT ErrorCode = 20002 // Invalid email format
	ErrorCode_ERROR_CODE_PROFILE_REGION_TOO_LONG      ErrorCode = 20003 // Region too long
	ErrorCode_ERROR_CODE_PROFILE_WHATS_UP_TOO_LONG    ErrorCode = 20004 // What's up message too long
	ErrorCode_ERROR_CODE_PROFILE_PHOTO_URL_TOO_LONG   ErrorCode = 20005 // Profile photo URL too long
	ErrorCode_ERROR_CODE_PROFILE_PEERS_ID_EMPTY       ErrorCode = 20006 // Peers ID cannot be empty
	ErrorCode_ERROR_CODE_PROFILE_PEERS_ID_INVALID     ErrorCode = 20007 // Peers ID format invalid
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "ERROR_CODE_UNSPECIFIED",
		10001: "ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT",
		10002: "ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE",
		10003: "ERROR_CODE_ACTOR_INVALID_NAME",
		10004: "ERROR_CODE_ACTOR_INVALID_EMAIL",
		10005: "ERROR_CODE_ACTOR_INVALID_PASSWORD",
		10006: "ERROR_CODE_ACTOR_ACTOR_EXISTS",
		10007: "ERROR_CODE_ACTOR_INVALID_PASSPORT",
		10008: "ERROR_CODE_ACTOR_NOT_FOUND",
		10009: "ERROR_CODE_ACTOR_INVALID_CREDENTIALS",
		10010: "ERROR_CODE_PEER_ADDR_EXISTS",
		20001: "ERROR_CODE_PROFILE_INVALID_GENDER",
		20002: "ERROR_CODE_PROFILE_INVALID_EMAIL_FORMAT",
		20003: "ERROR_CODE_PROFILE_REGION_TOO_LONG",
		20004: "ERROR_CODE_PROFILE_WHATS_UP_TOO_LONG",
		20005: "ERROR_CODE_PROFILE_PHOTO_URL_TOO_LONG",
		20006: "ERROR_CODE_PROFILE_PEERS_ID_EMPTY",
		20007: "ERROR_CODE_PROFILE_PEERS_ID_INVALID",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                        0,
		"ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT": 10001,
		"ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE": 10002,
		"ERROR_CODE_ACTOR_INVALID_NAME":                 10003,
		"ERROR_CODE_ACTOR_INVALID_EMAIL":                10004,
		"ERROR_CODE_ACTOR_INVALID_PASSWORD":             10005,
		"ERROR_CODE_ACTOR_ACTOR_EXISTS":                 10006,
		"ERROR_CODE_ACTOR_INVALID_PASSPORT":             10007,
		"ERROR_CODE_ACTOR_NOT_FOUND":                    10008,
		"ERROR_CODE_ACTOR_INVALID_CREDENTIALS":          10009,
		"ERROR_CODE_PEER_ADDR_EXISTS":                   10010,
		"ERROR_CODE_PROFILE_INVALID_GENDER":             20001,
		"ERROR_CODE_PROFILE_INVALID_EMAIL_FORMAT":       20002,
		"ERROR_CODE_PROFILE_REGION_TOO_LONG":            20003,
		"ERROR_CODE_PROFILE_WHATS_UP_TOO_LONG":          20004,
		"ERROR_CODE_PROFILE_PHOTO_URL_TOO_LONG":         20005,
		"ERROR_CODE_PROFILE_PEERS_ID_EMPTY":             20006,
		"ERROR_CODE_PROFILE_PEERS_ID_INVALID":           20007,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_touch_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_touch_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_touch_v1_errors_proto_rawDescGZIP(), []int{0}
}

// Error definition for Touch module
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code (e.g., "t10001")
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_touch_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_touch_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Error response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"` // Error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_touch_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

// Get error request
type GetErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // Error code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetErrorRequest) Reset() {
	*x = GetErrorRequest{}
	mi := &file_touch_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetErrorRequest) ProtoMessage() {}

func (x *GetErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetErrorRequest.ProtoReflect.Descriptor instead.
func (*GetErrorRequest) Descriptor() ([]byte, []int) {
	return file_touch_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *GetErrorRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Create error request
type CreateErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`       // Error code
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateErrorRequest) Reset() {
	*x = CreateErrorRequest{}
	mi := &file_touch_v1_errors_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateErrorRequest) ProtoMessage() {}

func (x *CreateErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_errors_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateErrorRequest.ProtoReflect.Descriptor instead.
func (*CreateErrorRequest) Descriptor() ([]byte, []int) {
	return file_touch_v1_errors_proto_rawDescGZIP(), []int{3}
}

func (x *CreateErrorRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateErrorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_touch_v1_errors_proto protoreflect.FileDescriptor

const file_touch_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x15touch/v1/errors.proto\x12\x14peers_touch.touch.v1\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\rErrorResponse\x121\n" +
	"\x05error\x18\x01 \x01(\v2\x1b.peers_touch.touch.v1.ErrorR\x05error\"%\n" +
	"\x0fGetErrorRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"B\n" +
	"\x12CreateErrorRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xe9\x05\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x122\n" +
	"-ERROR_CODE_WELL_KNOWN_INVALID_RESOURCE_FORMAT\x10\x91N\x122\n" +
	"-ERROR_CODE_WELL_KNOWN_UNSUPPORTED_PREFIX_TYPE\x10\x92N\x12\"\n" +
	"\x1dERROR_CODE_ACTOR_INVALID_NAME\x10\x93N\x12#\n" +
	"\x1eERROR_CODE_ACTOR_INVALID_EMAIL\x10\x94N\x12&\n" +
	"!ERROR_CODE_ACTOR_INVALID_PASSWORD\x10\x95N\x12\"\n" +
	"\x1dERROR_CODE_ACTOR_ACTOR_EXISTS\x10\x96N\x12&\n" +
	"!ERROR_CODE_ACTOR_INVALID_PASSPORT\x10\x97N\x12\x1f\n" +
	"\x1aERROR_CODE_ACTOR_NOT_FOUND\x10\x98N\x12)\n" +
	"$ERROR_CODE_ACTOR_INVALID_CREDENTIALS\x10\x99N\x12 \n" +
	"\x1bERROR_CODE_PEER_ADDR_EXISTS\x10\x9aN\x12'\n" +
	"!ERROR_CODE_PROFILE_INVALID_GENDER\x10\xa1\x9c\x01\x12-\n" +
	"'ERROR_CODE_PROFILE_INVALID_EMAIL_FORMAT\x10\xa2\x9c\x01\x12(\n" +
	"\"ERROR_CODE_PROFILE_REGION_TOO_LONG\x10\xa3\x9c\x01\x12*\n" +
	"$ERROR_CODE_PROFILE_WHATS_UP_TOO_LONG\x10\xa4\x9c\x01\x12+\n" +
	"%ERROR_CODE_PROFILE_PHOTO_URL_TOO_LONG\x10\xa5\x9c\x01\x12'\n" +
	"!ERROR_CODE_PROFILE_PEERS_ID_EMPTY\x10\xa6\x9c\x01\x12)\n" +
	"#ERROR_CODE_PROFILE_PEERS_ID_INVALID\x10\xa7\x9c\x012\xb4\x01\n" +
	"\fErrorService\x12N\n" +
	"\bGetError\x12%.peers_touch.touch.v1.GetErrorRequest\x1a\x1b.peers_touch.touch.v1.Error\x12T\n" +
	"\vCreateError\x12(.peers_touch.touch.v1.CreateErrorRequest\x1a\x1b.peers_touch.touch.v1.ErrorB?Z=github.com/peers-touch/peers-touch/proto/gen/touch/v1;touchv1b\x06proto3"

var (
	file_touch_v1_errors_proto_rawDescOnce sync.Once
	file_touch_v1_errors_proto_rawDescData []byte
)

func file_touch_v1_errors_proto_rawDescGZIP() []byte {
	file_touch_v1_errors_proto_rawDescOnce.Do(func() {
		file_touch_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_errors_proto_rawDesc), len(file_touch_v1_errors_proto_rawDesc)))
	})
	return file_touch_v1_errors_proto_rawDescData
}

var file_touch_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_touch_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_touch_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),             // 0: peers_touch.touch.v1.ErrorCode
	(*Error)(nil),              // 1: peers_touch.touch.v1.Error
	(*ErrorResponse)(nil),      // 2: peers_touch.touch.v1.ErrorResponse
	(*GetErrorRequest)(nil),    // 3: peers_touch.touch.v1.GetErrorRequest
	(*CreateErrorRequest)(nil), // 4: peers_touch.touch.v1.CreateErrorRequest
}
var file_touch_v1_errors_proto_depIdxs = []int32{
	1, // 0: peers_touch.touch.v1.ErrorResponse.error:type_name -> peers_touch.touch.v1.Error
	3, // 1: peers_touch.touch.v1.ErrorService.GetError:input_type -> peers_touch.touch.v1.GetErrorRequest
	4, // 2: peers_touch.touch.v1.ErrorService.CreateError:input_type -> peers_touch.touch.v1.CreateErrorRequest
	1, // 3: peers_touch.touch.v1.ErrorService.GetError:output_type -> peers_touch.touch.v1.Error
	1, // 4: peers_touch.touch.v1.ErrorService.CreateError:output_type -> peers_touch.touch.v1.Error
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_touch_v1_errors_proto_init() }
func file_touch_v1_errors_proto_init() {
	if File_touch_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_errors_proto_rawDesc), len(file_touch_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_v1_errors_proto_goTypes,
		DependencyIndexes: file_touch_v1_errors_proto_depIdxs,
		EnumInfos:         file_touch_v1_errors_proto_enumTypes,
		MessageInfos:      file_touch_v1_errors_proto_msgTypes,
	}.Build()
	File_touch_v1_errors_proto = out.File
	file_touch_v1_errors_proto_goTypes = nil
	file_touch_v1_errors_proto_depIdxs = nil
}
