// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: touch/v1/profile.proto

package touchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gender enumeration
type Gender int32

const (
	Gender_GENDER_UNSPECIFIED Gender = 0
	Gender_GENDER_MALE        Gender = 1
	Gender_GENDER_FEMALE      Gender = 2
	Gender_GENDER_OTHER       Gender = 3
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "GENDER_UNSPECIFIED",
		1: "GENDER_MALE",
		2: "GENDER_FEMALE",
		3: "GENDER_OTHER",
	}
	Gender_value = map[string]int32{
		"GENDER_UNSPECIFIED": 0,
		"GENDER_MALE":        1,
		"GENDER_FEMALE":      2,
		"GENDER_OTHER":       3,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_touch_v1_profile_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_touch_v1_profile_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_touch_v1_profile_proto_rawDescGZIP(), []int{0}
}

// User profile get response
type ProfileGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfilePhoto  string                 `protobuf:"bytes,1,opt,name=profile_photo,json=profilePhoto,proto3" json:"profile_photo,omitempty"`   // Profile photo URL
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                       // Name
	Gender        Gender                 `protobuf:"varint,3,opt,name=gender,proto3,enum=peers_touch.touch.v1.Gender" json:"gender,omitempty"` // Gender
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                                   // Region
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`                                     // Email
	PeersId       string                 `protobuf:"bytes,6,opt,name=peers_id,json=peersId,proto3" json:"peers_id,omitempty"`                  // Peers ID
	WhatsUp       string                 `protobuf:"bytes,7,opt,name=whats_up,json=whatsUp,proto3" json:"whats_up,omitempty"`                  // Personal signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileGetResponse) Reset() {
	*x = ProfileGetResponse{}
	mi := &file_touch_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGetResponse) ProtoMessage() {}

func (x *ProfileGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGetResponse.ProtoReflect.Descriptor instead.
func (*ProfileGetResponse) Descriptor() ([]byte, []int) {
	return file_touch_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileGetResponse) GetProfilePhoto() string {
	if x != nil {
		return x.ProfilePhoto
	}
	return ""
}

func (x *ProfileGetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProfileGetResponse) GetGender() Gender {
	if x != nil {
		return x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *ProfileGetResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ProfileGetResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileGetResponse) GetPeersId() string {
	if x != nil {
		return x.PeersId
	}
	return ""
}

func (x *ProfileGetResponse) GetWhatsUp() string {
	if x != nil {
		return x.WhatsUp
	}
	return ""
}

// User profile update parameters
type ProfileUpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProfilePhoto  *string                `protobuf:"bytes,1,opt,name=profile_photo,json=profilePhoto,proto3,oneof" json:"profile_photo,omitempty"`   // Profile photo URL (optional)
	Gender        *Gender                `protobuf:"varint,2,opt,name=gender,proto3,enum=peers_touch.touch.v1.Gender,oneof" json:"gender,omitempty"` // Gender (optional)
	Region        *string                `protobuf:"bytes,3,opt,name=region,proto3,oneof" json:"region,omitempty"`                                   // Region (optional)
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`                                     // Email (optional)
	WhatsUp       *string                `protobuf:"bytes,5,opt,name=whats_up,json=whatsUp,proto3,oneof" json:"whats_up,omitempty"`                  // Personal signature (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileUpdateParams) Reset() {
	*x = ProfileUpdateParams{}
	mi := &file_touch_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileUpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUpdateParams) ProtoMessage() {}

func (x *ProfileUpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_touch_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUpdateParams.ProtoReflect.Descriptor instead.
func (*ProfileUpdateParams) Descriptor() ([]byte, []int) {
	return file_touch_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileUpdateParams) GetProfilePhoto() string {
	if x != nil && x.ProfilePhoto != nil {
		return *x.ProfilePhoto
	}
	return ""
}

func (x *ProfileUpdateParams) GetGender() Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Gender_GENDER_UNSPECIFIED
}

func (x *ProfileUpdateParams) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *ProfileUpdateParams) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *ProfileUpdateParams) GetWhatsUp() string {
	if x != nil && x.WhatsUp != nil {
		return *x.WhatsUp
	}
	return ""
}

var File_touch_v1_profile_proto protoreflect.FileDescriptor

const file_touch_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x16touch/v1/profile.proto\x12\x14peers_touch.touch.v1\x1a\x14touch/v1/types.proto\"\xe7\x01\n" +
	"\x12ProfileGetResponse\x12#\n" +
	"\rprofile_photo\x18\x01 \x01(\tR\fprofilePhoto\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x124\n" +
	"\x06gender\x18\x03 \x01(\x0e2\x1c.peers_touch.touch.v1.GenderR\x06gender\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x19\n" +
	"\bpeers_id\x18\x06 \x01(\tR\apeersId\x12\x19\n" +
	"\bwhats_up\x18\a \x01(\tR\awhatsUp\"\x91\x02\n" +
	"\x13ProfileUpdateParams\x12(\n" +
	"\rprofile_photo\x18\x01 \x01(\tH\x00R\fprofilePhoto\x88\x01\x01\x129\n" +
	"\x06gender\x18\x02 \x01(\x0e2\x1c.peers_touch.touch.v1.GenderH\x01R\x06gender\x88\x01\x01\x12\x1b\n" +
	"\x06region\x18\x03 \x01(\tH\x02R\x06region\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x03R\x05email\x88\x01\x01\x12\x1e\n" +
	"\bwhats_up\x18\x05 \x01(\tH\x04R\awhatsUp\x88\x01\x01B\x10\n" +
	"\x0e_profile_photoB\t\n" +
	"\a_genderB\t\n" +
	"\a_regionB\b\n" +
	"\x06_emailB\v\n" +
	"\t_whats_up*V\n" +
	"\x06Gender\x12\x16\n" +
	"\x12GENDER_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vGENDER_MALE\x10\x01\x12\x11\n" +
	"\rGENDER_FEMALE\x10\x02\x12\x10\n" +
	"\fGENDER_OTHER\x10\x032\xcb\x01\n" +
	"\x0eProfileService\x12S\n" +
	"\n" +
	"GetProfile\x12\x1b.peers_touch.touch.v1.Empty\x1a(.peers_touch.touch.v1.ProfileGetResponse\x12d\n" +
	"\rUpdateProfile\x12).peers_touch.touch.v1.ProfileUpdateParams\x1a(.peers_touch.touch.v1.ProfileGetResponseB?Z=github.com/peers-touch/peers-touch/proto/gen/touch/v1;touchv1b\x06proto3"

var (
	file_touch_v1_profile_proto_rawDescOnce sync.Once
	file_touch_v1_profile_proto_rawDescData []byte
)

func file_touch_v1_profile_proto_rawDescGZIP() []byte {
	file_touch_v1_profile_proto_rawDescOnce.Do(func() {
		file_touch_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_touch_v1_profile_proto_rawDesc), len(file_touch_v1_profile_proto_rawDesc)))
	})
	return file_touch_v1_profile_proto_rawDescData
}

var file_touch_v1_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_touch_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_touch_v1_profile_proto_goTypes = []any{
	(Gender)(0),                 // 0: peers_touch.touch.v1.Gender
	(*ProfileGetResponse)(nil),  // 1: peers_touch.touch.v1.ProfileGetResponse
	(*ProfileUpdateParams)(nil), // 2: peers_touch.touch.v1.ProfileUpdateParams
	(*Empty)(nil),               // 3: peers_touch.touch.v1.Empty
}
var file_touch_v1_profile_proto_depIdxs = []int32{
	0, // 0: peers_touch.touch.v1.ProfileGetResponse.gender:type_name -> peers_touch.touch.v1.Gender
	0, // 1: peers_touch.touch.v1.ProfileUpdateParams.gender:type_name -> peers_touch.touch.v1.Gender
	3, // 2: peers_touch.touch.v1.ProfileService.GetProfile:input_type -> peers_touch.touch.v1.Empty
	2, // 3: peers_touch.touch.v1.ProfileService.UpdateProfile:input_type -> peers_touch.touch.v1.ProfileUpdateParams
	1, // 4: peers_touch.touch.v1.ProfileService.GetProfile:output_type -> peers_touch.touch.v1.ProfileGetResponse
	1, // 5: peers_touch.touch.v1.ProfileService.UpdateProfile:output_type -> peers_touch.touch.v1.ProfileGetResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_touch_v1_profile_proto_init() }
func file_touch_v1_profile_proto_init() {
	if File_touch_v1_profile_proto != nil {
		return
	}
	file_touch_v1_types_proto_init()
	file_touch_v1_profile_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_touch_v1_profile_proto_rawDesc), len(file_touch_v1_profile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_touch_v1_profile_proto_goTypes,
		DependencyIndexes: file_touch_v1_profile_proto_depIdxs,
		EnumInfos:         file_touch_v1_profile_proto_enumTypes,
		MessageInfos:      file_touch_v1_profile_proto_msgTypes,
	}.Build()
	File_touch_v1_profile_proto = out.File
	file_touch_v1_profile_proto_goTypes = nil
	file_touch_v1_profile_proto_depIdxs = nil
}
