// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: aibox/v1/types.proto

package aiboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Standard provider types supported
type ProviderType int32

const (
	ProviderType_PROVIDER_TYPE_UNSPECIFIED ProviderType = 0
	ProviderType_PROVIDER_TYPE_OPENAI      ProviderType = 1
	ProviderType_PROVIDER_TYPE_ANTHROPIC   ProviderType = 2
	ProviderType_PROVIDER_TYPE_OLLAMA      ProviderType = 3
	ProviderType_PROVIDER_TYPE_CUSTOM      ProviderType = 9
)

// Enum value maps for ProviderType.
var (
	ProviderType_name = map[int32]string{
		0: "PROVIDER_TYPE_UNSPECIFIED",
		1: "PROVIDER_TYPE_OPENAI",
		2: "PROVIDER_TYPE_ANTHROPIC",
		3: "PROVIDER_TYPE_OLLAMA",
		9: "PROVIDER_TYPE_CUSTOM",
	}
	ProviderType_value = map[string]int32{
		"PROVIDER_TYPE_UNSPECIFIED": 0,
		"PROVIDER_TYPE_OPENAI":      1,
		"PROVIDER_TYPE_ANTHROPIC":   2,
		"PROVIDER_TYPE_OLLAMA":      3,
		"PROVIDER_TYPE_CUSTOM":      9,
	}
)

func (x ProviderType) Enum() *ProviderType {
	p := new(ProviderType)
	*p = x
	return p
}

func (x ProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_aibox_v1_types_proto_enumTypes[0].Descriptor()
}

func (ProviderType) Type() protoreflect.EnumType {
	return &file_aibox_v1_types_proto_enumTypes[0]
}

func (x ProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderType.Descriptor instead.
func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return file_aibox_v1_types_proto_rawDescGZIP(), []int{0}
}

// Provider runtime configuration; returned with key material omitted by server
type ProviderConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiKey         string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`                          // server should omit in responses for safety
	Endpoint       string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`                                    // base URL
	ProxyUrl       string                 `protobuf:"bytes,3,opt,name=proxy_url,json=proxyUrl,proto3" json:"proxy_url,omitempty"`                    // optional proxy URL
	TimeoutSeconds int32                  `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // request timeout
	MaxRetries     int32                  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`             // retry limit
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderConfig) Reset() {
	*x = ProviderConfig{}
	mi := &file_aibox_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderConfig) ProtoMessage() {}

func (x *ProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aibox_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderConfig.ProtoReflect.Descriptor instead.
func (*ProviderConfig) Descriptor() ([]byte, []int) {
	return file_aibox_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ProviderConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ProviderConfig) GetProxyUrl() string {
	if x != nil {
		return x.ProxyUrl
	}
	return ""
}

func (x *ProviderConfig) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProviderConfig) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

// AI provider record
type AiProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ProviderType           `protobuf:"varint,2,opt,name=type,proto3,enum=peers.aibox.v1.ProviderType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	LogoUrl       string                 `protobuf:"bytes,7,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Sort          int32                  `protobuf:"varint,8,opt,name=sort,proto3" json:"sort,omitempty"`
	Config        *ProviderConfig        `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiProvider) Reset() {
	*x = AiProvider{}
	mi := &file_aibox_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiProvider) ProtoMessage() {}

func (x *AiProvider) ProtoReflect() protoreflect.Message {
	mi := &file_aibox_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiProvider.ProtoReflect.Descriptor instead.
func (*AiProvider) Descriptor() ([]byte, []int) {
	return file_aibox_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *AiProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AiProvider) GetType() ProviderType {
	if x != nil {
		return x.Type
	}
	return ProviderType_PROVIDER_TYPE_UNSPECIFIED
}

func (x *AiProvider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AiProvider) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AiProvider) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AiProvider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AiProvider) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *AiProvider) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AiProvider) GetConfig() *ProviderConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *AiProvider) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AiProvider) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_aibox_v1_types_proto protoreflect.FileDescriptor

const file_aibox_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x14aibox/v1/types.proto\x12\x0epeers.aibox.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xac\x01\n" +
	"\x0eProviderConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tproxy_url\x18\x03 \x01(\tR\bproxyUrl\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\"\x9e\x03\n" +
	"\n" +
	"AiProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.peers.aibox.v1.ProviderTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x19\n" +
	"\blogo_url\x18\a \x01(\tR\alogoUrl\x12\x12\n" +
	"\x04sort\x18\b \x01(\x05R\x04sort\x126\n" +
	"\x06config\x18\t \x01(\v2\x1e.peers.aibox.v1.ProviderConfigR\x06config\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\x98\x01\n" +
	"\fProviderType\x12\x1d\n" +
	"\x19PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PROVIDER_TYPE_OPENAI\x10\x01\x12\x1b\n" +
	"\x17PROVIDER_TYPE_ANTHROPIC\x10\x02\x12\x18\n" +
	"\x14PROVIDER_TYPE_OLLAMA\x10\x03\x12\x18\n" +
	"\x14PROVIDER_TYPE_CUSTOM\x10\tB?Z=github.com/peers-touch/peers-touch/proto/gen/aibox/v1;aiboxv1b\x06proto3"

var (
	file_aibox_v1_types_proto_rawDescOnce sync.Once
	file_aibox_v1_types_proto_rawDescData []byte
)

func file_aibox_v1_types_proto_rawDescGZIP() []byte {
	file_aibox_v1_types_proto_rawDescOnce.Do(func() {
		file_aibox_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aibox_v1_types_proto_rawDesc), len(file_aibox_v1_types_proto_rawDesc)))
	})
	return file_aibox_v1_types_proto_rawDescData
}

var file_aibox_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aibox_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aibox_v1_types_proto_goTypes = []any{
	(ProviderType)(0),             // 0: peers.aibox.v1.ProviderType
	(*ProviderConfig)(nil),        // 1: peers.aibox.v1.ProviderConfig
	(*AiProvider)(nil),            // 2: peers.aibox.v1.AiProvider
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_aibox_v1_types_proto_depIdxs = []int32{
	0, // 0: peers.aibox.v1.AiProvider.type:type_name -> peers.aibox.v1.ProviderType
	1, // 1: peers.aibox.v1.AiProvider.config:type_name -> peers.aibox.v1.ProviderConfig
	3, // 2: peers.aibox.v1.AiProvider.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: peers.aibox.v1.AiProvider.updated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aibox_v1_types_proto_init() }
func file_aibox_v1_types_proto_init() {
	if File_aibox_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aibox_v1_types_proto_rawDesc), len(file_aibox_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aibox_v1_types_proto_goTypes,
		DependencyIndexes: file_aibox_v1_types_proto_depIdxs,
		EnumInfos:         file_aibox_v1_types_proto_enumTypes,
		MessageInfos:      file_aibox_v1_types_proto_msgTypes,
	}.Build()
	File_aibox_v1_types_proto = out.File
	file_aibox_v1_types_proto_goTypes = nil
	file_aibox_v1_types_proto_depIdxs = nil
}
