// PEERS_GENERATION_CONFIG:
//   targets: [backend, desktop]
//   model_only: true

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: v1/peers_touch_station/ai_box/service.proto

package ai_box

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v1_peers_touch_station_ai_box_service_proto protoreflect.FileDescriptor

const file_v1_peers_touch_station_ai_box_service_proto_rawDesc = "" +
	"\n" +
	"+v1/peers_touch_station/ai_box/service.proto\x12)peers_touch.v1.peers_touch_station.ai_box\x1a\x1fgoogle/protobuf/timestamp.proto\x1a,v1/peers_touch_station/ai_box/provider.proto2\xfb\n" +
	"\n" +
	"\fAiBoxService\x12\x95\x01\n" +
	"\x0eCreateProvider\x12@.peers_touch.v1.peers_touch_station.ai_box.CreateProviderRequest\x1aA.peers_touch.v1.peers_touch_station.ai_box.CreateProviderResponse\x12\x95\x01\n" +
	"\x0eUpdateProvider\x12@.peers_touch.v1.peers_touch_station.ai_box.UpdateProviderRequest\x1aA.peers_touch.v1.peers_touch_station.ai_box.UpdateProviderResponse\x12\x95\x01\n" +
	"\x0eDeleteProvider\x12@.peers_touch.v1.peers_touch_station.ai_box.DeleteProviderRequest\x1aA.peers_touch.v1.peers_touch_station.ai_box.DeleteProviderResponse\x12\x92\x01\n" +
	"\rListProviders\x12?.peers_touch.v1.peers_touch_station.ai_box.ListProvidersRequest\x1a@.peers_touch.v1.peers_touch_station.ai_box.ListProvidersResponse\x12\x8c\x01\n" +
	"\vGetProvider\x12=.peers_touch.v1.peers_touch_station.ai_box.GetProviderRequest\x1a>.peers_touch.v1.peers_touch_station.ai_box.GetProviderResponse\x12\x8f\x01\n" +
	"\fTestProvider\x12>.peers_touch.v1.peers_touch_station.ai_box.TestProviderRequest\x1a?.peers_touch.v1.peers_touch_station.ai_box.TestProviderResponse\x12\xa1\x01\n" +
	"\x12ListProviderModels\x12D.peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsRequest\x1aE.peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsResponse\x12\xa4\x01\n" +
	"\x13UpdateProviderModel\x12E.peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelRequest\x1aF.peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelResponse\x12\xa1\x01\n" +
	"\x12SyncProviderModels\x12D.peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsRequest\x1aE.peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsResponseBHZFgithub.com/peers-touch/peers-touch/proto/v1/peers_touch_station/ai_boxb\x06proto3"

var file_v1_peers_touch_station_ai_box_service_proto_goTypes = []any{
	(*CreateProviderRequest)(nil),       // 0: peers_touch.v1.peers_touch_station.ai_box.CreateProviderRequest
	(*UpdateProviderRequest)(nil),       // 1: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderRequest
	(*DeleteProviderRequest)(nil),       // 2: peers_touch.v1.peers_touch_station.ai_box.DeleteProviderRequest
	(*ListProvidersRequest)(nil),        // 3: peers_touch.v1.peers_touch_station.ai_box.ListProvidersRequest
	(*GetProviderRequest)(nil),          // 4: peers_touch.v1.peers_touch_station.ai_box.GetProviderRequest
	(*TestProviderRequest)(nil),         // 5: peers_touch.v1.peers_touch_station.ai_box.TestProviderRequest
	(*ListProviderModelsRequest)(nil),   // 6: peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsRequest
	(*UpdateProviderModelRequest)(nil),  // 7: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelRequest
	(*SyncProviderModelsRequest)(nil),   // 8: peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsRequest
	(*CreateProviderResponse)(nil),      // 9: peers_touch.v1.peers_touch_station.ai_box.CreateProviderResponse
	(*UpdateProviderResponse)(nil),      // 10: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderResponse
	(*DeleteProviderResponse)(nil),      // 11: peers_touch.v1.peers_touch_station.ai_box.DeleteProviderResponse
	(*ListProvidersResponse)(nil),       // 12: peers_touch.v1.peers_touch_station.ai_box.ListProvidersResponse
	(*GetProviderResponse)(nil),         // 13: peers_touch.v1.peers_touch_station.ai_box.GetProviderResponse
	(*TestProviderResponse)(nil),        // 14: peers_touch.v1.peers_touch_station.ai_box.TestProviderResponse
	(*ListProviderModelsResponse)(nil),  // 15: peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsResponse
	(*UpdateProviderModelResponse)(nil), // 16: peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelResponse
	(*SyncProviderModelsResponse)(nil),  // 17: peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsResponse
}
var file_v1_peers_touch_station_ai_box_service_proto_depIdxs = []int32{
	0,  // 0: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.CreateProvider:input_type -> peers_touch.v1.peers_touch_station.ai_box.CreateProviderRequest
	1,  // 1: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.UpdateProvider:input_type -> peers_touch.v1.peers_touch_station.ai_box.UpdateProviderRequest
	2,  // 2: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.DeleteProvider:input_type -> peers_touch.v1.peers_touch_station.ai_box.DeleteProviderRequest
	3,  // 3: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.ListProviders:input_type -> peers_touch.v1.peers_touch_station.ai_box.ListProvidersRequest
	4,  // 4: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.GetProvider:input_type -> peers_touch.v1.peers_touch_station.ai_box.GetProviderRequest
	5,  // 5: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.TestProvider:input_type -> peers_touch.v1.peers_touch_station.ai_box.TestProviderRequest
	6,  // 6: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.ListProviderModels:input_type -> peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsRequest
	7,  // 7: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.UpdateProviderModel:input_type -> peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelRequest
	8,  // 8: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.SyncProviderModels:input_type -> peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsRequest
	9,  // 9: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.CreateProvider:output_type -> peers_touch.v1.peers_touch_station.ai_box.CreateProviderResponse
	10, // 10: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.UpdateProvider:output_type -> peers_touch.v1.peers_touch_station.ai_box.UpdateProviderResponse
	11, // 11: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.DeleteProvider:output_type -> peers_touch.v1.peers_touch_station.ai_box.DeleteProviderResponse
	12, // 12: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.ListProviders:output_type -> peers_touch.v1.peers_touch_station.ai_box.ListProvidersResponse
	13, // 13: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.GetProvider:output_type -> peers_touch.v1.peers_touch_station.ai_box.GetProviderResponse
	14, // 14: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.TestProvider:output_type -> peers_touch.v1.peers_touch_station.ai_box.TestProviderResponse
	15, // 15: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.ListProviderModels:output_type -> peers_touch.v1.peers_touch_station.ai_box.ListProviderModelsResponse
	16, // 16: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.UpdateProviderModel:output_type -> peers_touch.v1.peers_touch_station.ai_box.UpdateProviderModelResponse
	17, // 17: peers_touch.v1.peers_touch_station.ai_box.AiBoxService.SyncProviderModels:output_type -> peers_touch.v1.peers_touch_station.ai_box.SyncProviderModelsResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v1_peers_touch_station_ai_box_service_proto_init() }
func file_v1_peers_touch_station_ai_box_service_proto_init() {
	if File_v1_peers_touch_station_ai_box_service_proto != nil {
		return
	}
	file_v1_peers_touch_station_ai_box_provider_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_peers_touch_station_ai_box_service_proto_rawDesc), len(file_v1_peers_touch_station_ai_box_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_peers_touch_station_ai_box_service_proto_goTypes,
		DependencyIndexes: file_v1_peers_touch_station_ai_box_service_proto_depIdxs,
	}.Build()
	File_v1_peers_touch_station_ai_box_service_proto = out.File
	file_v1_peers_touch_station_ai_box_service_proto_goTypes = nil
	file_v1_peers_touch_station_ai_box_service_proto_depIdxs = nil
}
